#!/usr/bin/env python3
"""Build ChangeForge runtime skills into deterministic dist/ layouts."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from validation_utils import ValidationProblem, load_yaml_file, parse_frontmatter


ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "src"
REGISTRY_DIR = SRC_DIR / "registry"
HOOK_RUNTIME_ROOT = SRC_DIR / "hook-runtime"
DIST_DIR = ROOT / "dist"
UNIVERSAL_SKILLS_ROOT = DIST_DIR / "universal" / "skills"
OPENAI_ZIP_DIR = DIST_DIR / "openai-api" / "zips"
BUILD_MANIFEST_NAME = ".changeforge-build-manifest.json"
GENERATED_MARKER = "<!-- Generated by scripts/build.py; do not edit by hand. -->"
ZIP_TIMESTAMP = (2024, 1, 1, 0, 0, 0)
MAX_ZIP_FILES = 500
MAX_ZIP_BYTES = 5 * 1024 * 1024
MAX_ZIP_FILE_BYTES = 2 * 1024 * 1024
PROFILES = ("recommended", "full", "dev")

AGENT_SKILL_ROOTS = (
    DIST_DIR / "codex" / "project" / ".agents" / "skills",
    DIST_DIR / "codex" / "user" / ".agents" / "skills",
    DIST_DIR / "codex" / "admin" / "skills",
    DIST_DIR / "claude" / "project" / ".claude" / "skills",
    DIST_DIR / "claude" / "user" / ".claude" / "skills",
    DIST_DIR / "copilot" / "project" / ".github" / "skills",
    DIST_DIR / "copilot" / "user" / ".copilot" / "skills",
)

HOOK_OUTPUT_ROOTS = {
    ("codex", "project"): DIST_DIR / "codex" / "project" / ".codex",
    ("claude", "project"): DIST_DIR / "claude" / "project" / ".claude",
}
BOOTSTRAP_TEMPLATE = (
    HOOK_RUNTIME_ROOT / "templates" / "bootstrap" / "changeforge-route-preflight.md"
)
BOOTSTRAP_FRAGMENT_NAME = "changeforge-route-preflight.md"
UNIVERSAL_BOOTSTRAP_ROOT = DIST_DIR / "universal" / "bootstrap"


@dataclass(frozen=True)
class RuntimeItem:
    name: str
    path: Path
    kind: str
    description: str
    version: str
    metadata: dict[str, Any]
    body: str


@dataclass(frozen=True)
class Capability(RuntimeItem):
    capability_id: str
    group: str
    used_by: tuple[str, ...]
    triggers: tuple[str, ...]
    risk_notes: tuple[str, ...]
    expected_outputs: tuple[str, ...]


def main() -> int:
    parser = argparse.ArgumentParser(description="Build ChangeForge runtime artifacts.")
    parser.add_argument(
        "--profile",
        choices=PROFILES,
        default="recommended",
        help="Runtime profile to build.",
    )
    args = parser.parse_args()

    try:
        build_result = build_profile(args.profile)
    except BuildError as exc:
        print(f"build: ERROR: {exc}", file=sys.stderr)
        return 1

    print(
        "build: built profile "
        f"{args.profile} with {build_result['professional_count']} professional skill(s), "
        f"{build_result['compiled_capability_count']} compiled foundation capability reference(s), "
        f"{build_result['domain_extension_count']} domain extension(s), "
        f"and {build_result['zip_count']} OpenAI API zip(s)."
    )
    return 0


class BuildError(Exception):
    """Raised when build inputs are malformed or unsafe."""


def build_profile(profile: str) -> dict[str, int]:
    registries = _load_registries()
    professional_skills = _load_runtime_items(
        registries["skills"],
        expected_kind="professional-skill",
    )
    domain_extensions = _load_runtime_items(
        registries["domain_extensions"],
        expected_kind="domain-extension",
    )
    capabilities = _load_capabilities(registries["capabilities"])
    routing_rules = registries["routing_rules"]

    top_level_items = _top_level_items(profile, professional_skills, capabilities, domain_extensions)
    compiled_capability_names = _build_all_runtime_roots(
        profile,
        top_level_items,
        professional_skills,
        capabilities,
        domain_extensions,
        routing_rules,
    )
    _build_hook_runtime()
    _cleanup_legacy_openai_zips(OPENAI_ZIP_DIR)
    zip_count = _package_openai_zips(
        UNIVERSAL_SKILLS_ROOT / profile,
        OPENAI_ZIP_DIR / profile,
    )

    return {
        "professional_count": len(professional_skills),
        "compiled_capability_count": len(compiled_capability_names),
        "domain_extension_count": len(domain_extensions),
        "zip_count": zip_count,
    }


def _load_registries() -> dict[str, list[dict[str, Any]]]:
    registry_specs = {
        "skills": ("skills.yaml", "skills"),
        "capabilities": ("capabilities.yaml", "capabilities"),
        "domain_extensions": ("domain-extensions.yaml", "domain_extensions"),
        "routing_rules": ("routing-rules.yaml", "routing_rules"),
    }
    registries: dict[str, list[dict[str, Any]]] = {}

    for logical_name, (file_name, key) in registry_specs.items():
        path = REGISTRY_DIR / file_name
        if not path.is_file():
            raise BuildError(f"missing registry file: {path.relative_to(ROOT)}")
        data = load_yaml_file(path)
        if not isinstance(data, dict):
            raise BuildError(f"{path.relative_to(ROOT)} must be a mapping")
        entries = data.get(key, [])
        if not isinstance(entries, list):
            raise BuildError(f"{path.relative_to(ROOT)} field '{key}' must be a list")
        normalized: list[dict[str, Any]] = []
        for index, entry in enumerate(entries):
            if not isinstance(entry, dict):
                raise BuildError(f"{file_name}:{key}[{index}] must be a mapping")
            normalized.append(entry)
        registries[logical_name] = normalized

    return registries


def _load_runtime_items(
    entries: list[dict[str, Any]],
    expected_kind: str,
) -> list[RuntimeItem]:
    items: list[RuntimeItem] = []
    seen_names: set[str] = set()

    for index, entry in enumerate(entries):
        name = _required_string(entry, "name", f"{expected_kind}[{index}]")
        rel_path = _required_string(entry, "path", f"{expected_kind}[{index}]")
        source_path = ROOT / rel_path
        item = _load_runtime_item(name, source_path, expected_kind)
        if item.name in seen_names:
            raise BuildError(f"duplicate runtime item name: {item.name}")
        seen_names.add(item.name)
        items.append(item)

    return items


def _load_runtime_item(name: str, source_path: Path, expected_kind: str) -> RuntimeItem:
    skill_file = source_path / "SKILL.md"
    if not skill_file.is_file():
        raise BuildError(f"{source_path.relative_to(ROOT)} is missing SKILL.md")

    try:
        metadata, _raw_frontmatter, body = parse_frontmatter(skill_file)
    except ValidationProblem as exc:
        raise BuildError(str(exc).replace(str(ROOT) + "/", "")) from exc

    actual_name = metadata.get("name")
    if actual_name != name:
        raise BuildError(f"{skill_file.relative_to(ROOT)} name does not match registry entry")

    kind = metadata.get("changeforge_kind")
    if kind != expected_kind:
        raise BuildError(
            f"{skill_file.relative_to(ROOT)} kind must be {expected_kind}, got {kind!r}"
        )

    description = metadata.get("description")
    version = metadata.get("changeforge_version")
    if not isinstance(description, str) or not description.strip():
        raise BuildError(f"{skill_file.relative_to(ROOT)} is missing description")
    if not isinstance(version, str) or not version.strip():
        raise BuildError(f"{skill_file.relative_to(ROOT)} is missing changeforge_version")

    return RuntimeItem(
        name=name,
        path=source_path,
        kind=expected_kind,
        description=description.strip(),
        version=version.strip(),
        metadata=metadata,
        body=body,
    )


def _load_capabilities(entries: list[dict[str, Any]]) -> list[Capability]:
    capabilities: list[Capability] = []
    seen_names: set[str] = set()
    seen_ids: set[str] = set()

    for index, entry in enumerate(entries):
        context = f"capabilities[{index}]"
        name = _required_string(entry, "name", context)
        rel_path = _required_string(entry, "path", context)
        base = _load_runtime_item(name, ROOT / rel_path, "foundation-capability")
        capability_id = _required_string(entry, "id", context)
        group = _required_string(entry, "group", context)

        if capability_id in seen_ids:
            raise BuildError(f"duplicate capability id: {capability_id}")
        if name in seen_names:
            raise BuildError(f"duplicate capability name: {name}")
        seen_ids.add(capability_id)
        seen_names.add(name)

        capabilities.append(
            Capability(
                name=base.name,
                path=base.path,
                kind=base.kind,
                description=base.description,
                version=base.version,
                metadata=base.metadata,
                body=base.body,
                capability_id=capability_id,
                group=group,
                used_by=tuple(_string_list(entry.get("used_by"), context, "used_by")),
                triggers=tuple(_string_list(entry.get("triggers"), context, "triggers")),
                risk_notes=tuple(_string_list(entry.get("risk_notes"), context, "risk_notes")),
                expected_outputs=tuple(
                    _string_list(entry.get("expected_outputs"), context, "expected_outputs")
                ),
            )
        )

    return capabilities


def _required_string(entry: dict[str, Any], key: str, context: str) -> str:
    value = entry.get(key)
    if not isinstance(value, str) or not value.strip():
        raise BuildError(f"{context}: missing string field '{key}'")
    return value.strip()


def _string_list(value: Any, context: str, key: str) -> list[str]:
    if not isinstance(value, list) or not all(isinstance(item, str) and item.strip() for item in value):
        raise BuildError(f"{context}: field '{key}' must be a list of strings")
    return [item.strip() for item in value]


def _top_level_items(
    profile: str,
    professional_skills: list[RuntimeItem],
    capabilities: list[Capability],
    domain_extensions: list[RuntimeItem],
) -> list[RuntimeItem]:
    if profile == "recommended":
        return [*professional_skills]
    if profile == "full":
        return [*professional_skills, *domain_extensions]
    if profile == "dev":
        return [*professional_skills, *capabilities, *domain_extensions]
    raise BuildError(f"unsupported profile: {profile}")


def _build_all_runtime_roots(
    profile: str,
    top_level_items: list[RuntimeItem],
    professional_skills: list[RuntimeItem],
    capabilities: list[Capability],
    domain_extensions: list[RuntimeItem],
    routing_rules: list[dict[str, Any]],
) -> set[str]:
    capability_map = _capabilities_by_professional_skill(capabilities)
    compiled_capability_names: set[str] = set()

    for root in (UNIVERSAL_SKILLS_ROOT, *AGENT_SKILL_ROOTS):
        profile_root = root / profile
        _reset_dir(profile_root)

        for item in top_level_items:
            destination = profile_root / item.name
            _copy_skill_tree(item.path, destination)
            if item.kind == "professional-skill":
                skill_capabilities = capability_map.get(item.name, [])
                _write_capability_references(destination, skill_capabilities)
                compiled_capability_names.update(capability.name for capability in skill_capabilities)
                if item.name == "change-forge-router":
                    _write_router_indexes(
                        destination,
                        professional_skills,
                        capabilities,
                        domain_extensions,
                        routing_rules,
                    )

        _write_build_manifest(
            profile_root,
            profile,
            top_level_items,
            professional_skills,
            capabilities,
            domain_extensions,
            compiled_capability_names,
        )

    return compiled_capability_names


def _capabilities_by_professional_skill(
    capabilities: list[Capability],
) -> dict[str, list[Capability]]:
    mapped: dict[str, list[Capability]] = {}
    for capability in capabilities:
        for skill_name in capability.used_by:
            mapped.setdefault(skill_name, []).append(capability)

    for skill_name, skill_capabilities in mapped.items():
        mapped[skill_name] = sorted(
            skill_capabilities,
            key=lambda capability: (
                capability.group,
                _capability_sort_id(capability),
                capability.name,
            ),
        )
    return mapped


def _capability_sort_id(capability: Capability) -> int:
    try:
        return int(capability.capability_id)
    except ValueError:
        return 0


def _reset_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def _copy_skill_tree(source: Path, destination: Path) -> None:
    def ignore(_directory: str, names: list[str]) -> set[str]:
        return {
            name
            for name in names
            if name in {".DS_Store", "__pycache__"} or name.endswith((".pyc", ".pyo"))
        }

    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination, ignore=ignore)


def _build_hook_runtime() -> None:
    if not HOOK_RUNTIME_ROOT.is_dir():
        raise BuildError(f"missing hook runtime source: {HOOK_RUNTIME_ROOT.relative_to(ROOT)}")
    if not BOOTSTRAP_TEMPLATE.is_file():
        raise BuildError(f"missing bootstrap template: {BOOTSTRAP_TEMPLATE.relative_to(ROOT)}")
    _build_codex_hook_runtime()
    _build_claude_hook_runtime()
    _build_universal_bootstrap()


def _build_codex_hook_runtime() -> None:
    target = HOOK_OUTPUT_ROOTS[("codex", "project")]
    hooks_dir = target / "hooks"
    _reset_dir(hooks_dir)
    _copy_hook_scripts(hooks_dir)
    shutil.copy2(
        HOOK_RUNTIME_ROOT / "templates" / "codex" / "hooks.json",
        target / "hooks.json",
    )
    _copy_bootstrap_fragment(target)
    _write_hook_manifest(target, agent="codex", scope="project")


def _build_claude_hook_runtime() -> None:
    target = HOOK_OUTPUT_ROOTS[("claude", "project")]
    hooks_dir = target / "hooks"
    _reset_dir(hooks_dir)
    _copy_hook_scripts(hooks_dir)
    shutil.copy2(
        HOOK_RUNTIME_ROOT
        / "templates"
        / "claude"
        / "settings.changeforge-hooks.fragment.json",
        target / "settings.changeforge-hooks.fragment.json",
    )
    _copy_bootstrap_fragment(target)
    _write_hook_manifest(target, agent="claude", scope="project")


def _build_universal_bootstrap() -> None:
    _reset_dir(UNIVERSAL_BOOTSTRAP_ROOT)
    shutil.copy2(
        BOOTSTRAP_TEMPLATE,
        UNIVERSAL_BOOTSTRAP_ROOT / BOOTSTRAP_FRAGMENT_NAME,
    )


def _copy_bootstrap_fragment(target: Path) -> None:
    target.mkdir(parents=True, exist_ok=True)
    shutil.copy2(BOOTSTRAP_TEMPLATE, target / BOOTSTRAP_FRAGMENT_NAME)


def _copy_hook_scripts(target: Path) -> None:
    scripts_dir = HOOK_RUNTIME_ROOT / "scripts"
    if not scripts_dir.is_dir():
        raise BuildError(f"missing hook script directory: {scripts_dir.relative_to(ROOT)}")
    for path in sorted(scripts_dir.glob("*.py")):
        destination = target / path.name
        shutil.copy2(path, destination)
        destination.chmod(0o755)


def _write_hook_manifest(target: Path, agent: str, scope: str) -> None:
    hooks = [
        "changeforge_post_edit_structure_gate",
        "changeforge_risk_surface_gate",
        "changeforge_stop_closure_gate",
    ]
    # Codex has no stable session-start hook, so the bootstrap reminder is wired
    # as a SessionStart hook for Claude only. Both runtimes still ship the
    # install-time bootstrap fragment for the advisory path.
    if agent == "claude":
        hooks = ["changeforge_session_bootstrap", *hooks]
    manifest = {
        "kind": "changeforge-hook-runtime",
        "agent": agent,
        "scope": scope,
        "source_version": _source_version(),
        "hooks": hooks,
        "bootstrap_fragment": BOOTSTRAP_FRAGMENT_NAME,
        "session_bootstrap_hook": agent == "claude",
    }
    (target / ".changeforge-hook-manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _write_capability_references(destination: Path, capabilities: list[Capability]) -> None:
    references_dir = destination / "references" / "capabilities"
    references_dir.mkdir(parents=True, exist_ok=True)

    for stale_file in references_dir.glob("*.md"):
        stale_file.unlink()

    index_lines = [
        GENERATED_MARKER,
        "",
        "# Compiled Foundation Capabilities",
        "",
    ]

    if not capabilities:
        index_lines.extend(
            [
                "No foundation capabilities are directly assigned to this professional skill.",
                "",
            ]
        )
    else:
        for capability in capabilities:
            file_name = f"{capability.capability_id}-{capability.name}.md"
            index_lines.append(
                f"- [{capability.capability_id} {capability.name}]({file_name})"
            )
            (references_dir / file_name).write_text(
                _render_capability_reference(capability),
                encoding="utf-8",
            )
        index_lines.append("")

    (references_dir / "index.md").write_text("\n".join(index_lines), encoding="utf-8")


def _render_capability_reference(capability: Capability) -> str:
    sections = _extract_sections(
        capability.body,
        (
            "Mission",
            "When To Use",
            "Non-Negotiable Rules",
            "Industry Benchmarks",
            "Helm Chart Release Controls",
            "Helm Pipeline Gate",
            "Selection Rules",
            "Risk Escalation Rules",
            "Critical Details",
            "Failure Modes",
            "Output Contract",
            "Quality Gate",
            "Completion Criteria",
        ),
    )

    lines = [
        GENERATED_MARKER,
        "",
        f"# {capability.name}",
        "",
        f"- Capability ID: {capability.capability_id}",
        f"- Group: {capability.group}",
        f"- Version: {capability.version}",
        f"- Used by: {', '.join(capability.used_by)}",
        f"- Triggers: {'; '.join(capability.triggers)}",
        f"- Risk notes: {'; '.join(capability.risk_notes)}",
        f"- Expected outputs: {'; '.join(capability.expected_outputs)}",
        "",
    ]

    for title, content in sections.items():
        lines.extend([f"## {title}", "", content.strip(), ""])

    return "\n".join(lines)


def _extract_sections(body: str, wanted_titles: tuple[str, ...]) -> dict[str, str]:
    wanted = {title.casefold(): title for title in wanted_titles}
    sections: dict[str, list[str]] = {}
    current_title: str | None = None

    for line in body.splitlines():
        match = re.match(r"^\s{0,3}#{1,6}\s+(.+?)\s*#*\s*$", line)
        if match:
            normalized = match.group(1).strip().casefold()
            current_title = wanted.get(normalized)
            if current_title and current_title not in sections:
                sections[current_title] = []
            continue

        if current_title:
            sections[current_title].append(line)

    return {
        title: "\n".join(sections[title]).strip()
        for title in wanted_titles
        if title in sections and "\n".join(sections[title]).strip()
    }


def _write_router_indexes(
    router_dir: Path,
    professional_skills: list[RuntimeItem],
    capabilities: list[Capability],
    domain_extensions: list[RuntimeItem],
    routing_rules: list[dict[str, Any]],
) -> None:
    references_dir = router_dir / "references"
    references_dir.mkdir(parents=True, exist_ok=True)
    (references_dir / "routing-rules.md").write_text(
        _render_routing_rules(routing_rules),
        encoding="utf-8",
    )
    (references_dir / "skill-registry.md").write_text(
        _render_skill_registry(professional_skills),
        encoding="utf-8",
    )
    (references_dir / "capability-index.md").write_text(
        _render_capability_index(capabilities),
        encoding="utf-8",
    )
    (references_dir / "domain-extension-index.md").write_text(
        _render_domain_extension_index(domain_extensions),
        encoding="utf-8",
    )


def _render_routing_rules(routing_rules: list[dict[str, Any]]) -> str:
    lines = [GENERATED_MARKER, "", "# Routing Rules", ""]
    for entry in sorted(
        routing_rules,
        key=lambda item: (-int(item.get("priority", 0)), str(item.get("route_to", ""))),
    ):
        route_to = entry.get("route_to", "")
        priority = entry.get("priority", "")
        lines.extend([f"## {route_to}", "", f"- Priority: {priority}"])
        triggers = entry.get("triggers", [])
        if isinstance(triggers, list) and triggers:
            lines.append("- Triggers:")
            lines.extend(f"  - {trigger}" for trigger in triggers if isinstance(trigger, str))
        lines.append("")
    return "\n".join(lines)


def _render_skill_registry(professional_skills: list[RuntimeItem]) -> str:
    lines = [GENERATED_MARKER, "", "# Skill Registry", ""]
    for skill in professional_skills:
        lines.extend(
            [
                f"## {skill.name}",
                "",
                f"- Kind: {skill.kind}",
                f"- Version: {skill.version}",
                f"- Description: {skill.description}",
                "",
            ]
        )
    return "\n".join(lines)


def _render_capability_index(capabilities: list[Capability]) -> str:
    lines = [GENERATED_MARKER, "", "# Capability Index", ""]
    grouped: dict[str, list[Capability]] = {}
    for capability in capabilities:
        grouped.setdefault(capability.group, []).append(capability)

    for group in sorted(grouped):
        lines.extend([f"## {group}", ""])
        for capability in sorted(grouped[group], key=_capability_sort_id):
            lines.extend(
                [
                    f"### {capability.capability_id} {capability.name}",
                    "",
                    f"- Version: {capability.version}",
                    f"- Used by: {', '.join(capability.used_by)}",
                    f"- Triggers: {'; '.join(capability.triggers)}",
                    f"- Risk notes: {'; '.join(capability.risk_notes)}",
                    f"- Expected outputs: {'; '.join(capability.expected_outputs)}",
                    "",
                ]
            )
    return "\n".join(lines)


def _render_domain_extension_index(domain_extensions: list[RuntimeItem]) -> str:
    lines = [GENERATED_MARKER, "", "# Domain Extension Index", ""]
    for extension in domain_extensions:
        lines.extend(
            [
                f"## {extension.name}",
                "",
                f"- Kind: {extension.kind}",
                f"- Version: {extension.version}",
                f"- Description: {extension.description}",
                "",
            ]
        )
    return "\n".join(lines)


def _write_build_manifest(
    profile_root: Path,
    profile: str,
    top_level_items: list[RuntimeItem],
    professional_skills: list[RuntimeItem],
    capabilities: list[Capability],
    domain_extensions: list[RuntimeItem],
    compiled_capability_names: set[str],
) -> None:
    manifest = {
        "profile": profile,
        "source_version": _source_version(),
        "foundation_mode": _foundation_mode(profile),
        "top_level_skills": [item.name for item in top_level_items],
        "professional_skills": [item.name for item in professional_skills],
        "foundation_capabilities": [capability.name for capability in capabilities],
        "compiled_foundation_capabilities": sorted(compiled_capability_names),
        "domain_extensions": [extension.name for extension in domain_extensions],
        "skill_versions": {item.name: item.version for item in top_level_items},
    }
    (profile_root / BUILD_MANIFEST_NAME).write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _foundation_mode(profile: str) -> str:
    if profile == "dev":
        return "top-level-and-compiled-references"
    return "compiled-references"


def _source_version() -> str:
    pyproject = ROOT / "pyproject.toml"
    if not pyproject.is_file():
        return "unknown"
    for line in pyproject.read_text(encoding="utf-8").splitlines():
        match = re.match(r'^version\s*=\s*"([^"]+)"', line.strip())
        if match:
            return match.group(1)
    return "unknown"


def _package_openai_zips(source_root: Path, zip_dir: Path) -> int:
    zip_dir.mkdir(parents=True, exist_ok=True)
    for stale_zip in zip_dir.glob("*.zip"):
        stale_zip.unlink()

    skill_dirs = [
        path
        for path in sorted(source_root.iterdir())
        if path.is_dir() and not path.name.startswith(".")
    ] if source_root.exists() else []

    for skill_dir in skill_dirs:
        _validate_zip_source(skill_dir)
        _write_skill_zip(skill_dir, zip_dir / f"{skill_dir.name}.zip")

    return len(skill_dirs)


def _cleanup_legacy_openai_zips(zip_root: Path) -> None:
    zip_root.mkdir(parents=True, exist_ok=True)
    for stale_zip in zip_root.glob("*.zip"):
        stale_zip.unlink()


def _validate_zip_source(skill_dir: Path) -> None:
    files = [path for path in sorted(skill_dir.rglob("*")) if path.is_file()]
    if len(files) > MAX_ZIP_FILES:
        raise BuildError(
            f"{skill_dir.relative_to(ROOT)} has {len(files)} files; max is {MAX_ZIP_FILES}"
        )
    if not (skill_dir / "SKILL.md").is_file():
        raise BuildError(f"{skill_dir.relative_to(ROOT)} is missing root SKILL.md")
    nested_skill_files = [path for path in files if path.name == "SKILL.md"]
    if nested_skill_files != [skill_dir / "SKILL.md"]:
        raise BuildError(f"{skill_dir.relative_to(ROOT)} must contain exactly one SKILL.md")

    total_size = 0
    for file_path in files:
        size = file_path.stat().st_size
        if size > MAX_ZIP_FILE_BYTES:
            raise BuildError(
                f"{file_path.relative_to(ROOT)} is {size} bytes; max is {MAX_ZIP_FILE_BYTES}"
            )
        total_size += size
    if total_size > MAX_ZIP_BYTES:
        raise BuildError(
            f"{skill_dir.relative_to(ROOT)} is {total_size} bytes; max is {MAX_ZIP_BYTES}"
        )


def _write_skill_zip(skill_dir: Path, zip_path: Path) -> None:
    files = [path for path in sorted(skill_dir.rglob("*")) if path.is_file()]
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for file_path in files:
            relative_path = file_path.relative_to(skill_dir)
            archive_name = f"{skill_dir.name}/{relative_path.as_posix()}"
            info = zipfile.ZipInfo(archive_name, ZIP_TIMESTAMP)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, file_path.read_bytes())


if __name__ == "__main__":
    raise SystemExit(main())
