#!/usr/bin/env python3
"""Build deterministic hookless rd-skills Skill and Agent Profile layouts."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
import tempfile
import tomllib
import zipfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

from validation_utils import (
    COMPILED_LAYER3_FORMAT,
    CORE_CONTRACTS,
    CORE_CONTRACTS_PATH,
    NAME_RE,
    PROFILE_CONTRACT_MODEL,
    PROMPT_CONTRACT_MODEL,
    REGISTRY_SCHEMA_VERSIONS,
    ROLE_CONTRACT_MODEL,
    TARGETED_REFERENCE_TABLE_COLUMNS,
    ValidationProblem,
    authoritative_build_input_snapshot,
    foundation_content_class_errors,
    foundation_ownership_errors,
    foundation_registry_field_errors,
    execution_level_runtime_reference_errors,
    load_yaml_file,
    parse_frontmatter,
    prompt_projection_errors,
    reference_contracts,
    reference_type_for_path,
    required_expertise_tag_errors,
    render_compact_markdown_table,
    render_targeted_reference_section,
    role_contract_map_errors,
)


ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT / "src"
REGISTRY_DIR = SRC_DIR / "registry"
DIST_DIR = ROOT / "dist"
UNIVERSAL_SKILLS_ROOT = DIST_DIR / "universal" / "skills"
OPENAI_ZIP_DIR = DIST_DIR / "openai-api" / "zips"
PROFILE_SOURCE = ROOT / PROFILE_CONTRACT_MODEL["source_path"]
HOST_ENFORCEMENT_SOURCE = SRC_DIR / "agent-profiles" / "host-enforcement.json"
CONTROL_PROMPT_SOURCE = ROOT / CORE_CONTRACTS["prompt_contract"]["path"]
BUILD_MANIFEST_NAME = ".changeforge-build-manifest.json"
GENERATED_MARKER = "<!-- Generated by scripts/build.py; do not edit by hand. -->"
ZIP_TIMESTAMP = (2024, 1, 1, 0, 0, 0)
MAX_ZIP_FILES = 500
MAX_ZIP_BYTES = 5 * 1024 * 1024
MAX_ZIP_FILE_BYTES = 2 * 1024 * 1024
MAX_RENDERED_PROFESSIONAL_BODY_LINES = 120
PROFILES = ("recommended", "full", "dev")
LAYER3_PROJECTION_SECTIONS = {
    "foundation": (
        ("Skill Role", "Decision Boundary"),
        ("High-Value Rules", "High-Value Rules"),
        ("Anti-Patterns", "Anti-Patterns"),
        ("Stop Conditions", "Stop Conditions"),
        ("Targeted References", "Targeted References"),
    ),
    "domain": (
        ("Role", "Decision Boundary"),
        ("Professional Decision Rules", "Professional Decision Rules"),
        ("High-Value Gotchas", "High-Value Gotchas"),
        ("Stop / Escalation Conditions", "Stop / Escalation Conditions"),
        ("Targeted References", "Targeted References"),
    ),
}
LAYER3_PROJECTION_FORBIDDEN_HEADINGS = frozenset(
    {
        "Registry Trigger",
        "Inputs",
        "Required Inputs",
        "Output Contract",
        "Execution Checklist",
        "When To Use",
        "Do Not Use",
    }
)
ENFORCEMENT_STATUSES = (
    "native-enforced",
    "sandbox-enforced",
    "prompt-enforced",
    "unsupported",
)
ENFORCEMENT_HOSTS = ("codex", "claude", "copilot", "cline", "openai-api")
ENFORCEMENT_CAPABILITIES = (
    "tool_allowlist",
    "workspace_write_protection",
    "read_only_command_semantics",
    "external_source_read",
)
HOST_ENFORCEMENT_CAPABILITIES = (
    "profile_delivery",
    "skill_loading",
    "subagent_dispatch",
    "partial_handoff",
    "isolated_workspace",
    "utility_no_edit",
)
GENERIC_CAPABILITY_CONTRACT = CORE_CONTRACTS["review_discipline_contract"][
    "generic_capability_contract"
]
DECISION_CAPABILITY_FIELDS = tuple(GENERIC_CAPABILITY_CONTRACT["injected_fields"])
DECISION_CAPABILITY_STATES = tuple(GENERIC_CAPABILITY_CONTRACT["states"])
HOST_MODE_VALUES = {
    "diff_input_mode": ("native", "supplied-artifact", "unsupported"),
    "validation_mode": ("native-read-only", "task-no-edit", "unsupported"),
}
NATIVE_DIFF_SAFEGUARDS = ("--no-pager", "--no-ext-diff", "--no-textconv")
EXTERNAL_READ_HOST_MODES = {
    "codex": "prompt-enforced",
    "claude": "native-enforced",
    "copilot": "unsupported",
    "cline": "unsupported",
    "openai-api": "unsupported",
}

LAYER_SOURCE_ROOTS = {
    "control": SRC_DIR / "control-skills",
    "professional": SRC_DIR / "professional-skills",
    "foundation": SRC_DIR / "foundation" / "capabilities",
    "domain": SRC_DIR / "domain-extensions",
}

REGISTRY_SPECS = {
    "control": ("control-skills.yaml", "changeforge.control_skills", "control_skills"),
    "professional": (
        "professional-skills.yaml",
        "changeforge.professional_skills",
        "professional_skills",
    ),
    "foundation": (
        "foundation-skills.yaml",
        "changeforge.foundation_skills",
        "foundation_skills",
    ),
    "domain": ("domain-skills.yaml", "changeforge.domain_skills", "domain_skills"),
}
REQUIRED_REGISTRY_FIELDS = (
    "name",
    "path",
    "role_support",
    "trigger_signals",
    "anti_trigger_signals",
    "required_inputs",
    "output_contract",
    "escalation_signals",
    "reference_index",
)

AGENT_SKILL_ROOTS = (
    DIST_DIR / "codex" / "project" / ".agents" / "skills",
    DIST_DIR / "codex" / "user" / ".agents" / "skills",
    DIST_DIR / "codex" / "admin" / "skills",
    DIST_DIR / "claude" / "project" / ".claude" / "skills",
    DIST_DIR / "claude" / "user" / ".claude" / "skills",
    DIST_DIR / "copilot" / "project" / ".github" / "skills",
    DIST_DIR / "copilot" / "user" / ".copilot" / "skills",
    DIST_DIR / "cline" / "project" / ".cline" / "skills",
    DIST_DIR / "cline" / "user" / ".cline" / "skills",
)

AGENT_PROFILE_OUTPUTS = (
    ("codex", DIST_DIR / "codex" / "project" / ".codex" / "agents"),
    ("codex", DIST_DIR / "codex" / "user" / ".codex" / "agents"),
    ("codex", DIST_DIR / "codex" / "admin" / "agents"),
    ("claude", DIST_DIR / "claude" / "project" / ".claude" / "agents"),
    ("claude", DIST_DIR / "claude" / "user" / ".claude" / "agents"),
    ("copilot", DIST_DIR / "copilot" / "project" / ".github" / "agents"),
    ("copilot", DIST_DIR / "copilot" / "user" / ".copilot" / "agents"),
)

@dataclass(frozen=True)
class SkillItem:
    name: str
    path: Path
    layer: str
    description: str
    metadata: dict[str, Any]
    body: str
    registry: dict[str, Any]


class BuildError(Exception):
    """Raised when build inputs are malformed or unsafe."""


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build hookless rd-skills Skills and Agent Profiles."
    )
    parser.add_argument("--profile", choices=PROFILES, default="recommended")
    args = parser.parse_args()

    try:
        result = build_profile(args.profile)
    except BuildError as exc:
        print(f"build: ERROR: {exc}", file=sys.stderr)
        return 1

    print(
        "build: built hookless profile "
        f"{args.profile} with {result['top_level_count']} standard Skill(s), "
        f"{result['compiled_layer3_reference_count']} compiled Layer 3 reference(s), "
        f"{result['agent_profile_count']} Agent Profile(s), and "
        f"{result['zip_count']} OpenAI API zip(s)."
    )
    return 0


def build_profile(profile: str) -> dict[str, Any]:
    if profile not in PROFILES:
        raise BuildError(f"unsupported profile: {profile}")

    # Nothing below this preflight may mutate a managed output. In particular,
    # the build also writes hosted-runtime zips, so their path chain must be
    # checked before the first profile reset rather than at packaging time.
    _preflight_static_paths(profile)
    registries = _load_registries()
    _preflight_registry_entries(registries)
    items = {
        layer: _load_items(layer, entries)
        for layer, entries in registries.items()
    }
    _validate_global_skill_names(items)
    profiles = _load_agent_profiles()
    enforcement = _load_host_enforcement()
    top_level = _top_level_items(profile, items)
    _preflight_build_plan(profile, top_level, items, profiles, enforcement)
    try:
        source_snapshot = authoritative_build_input_snapshot(ROOT)
    except (OSError, ValueError) as exc:
        raise BuildError(f"cannot snapshot authoritative build inputs: {exc}") from exc

    _clean_legacy_dist_artifacts()
    compiled_names = _build_skill_roots(
        profile,
        top_level,
        items,
        profiles,
        enforcement,
        source_snapshot,
    )
    _build_agent_profiles(profiles, enforcement)
    _reset_dir(OPENAI_ZIP_DIR / profile)
    _cleanup_legacy_zip_layout()
    zip_count = _package_openai_zips(
        UNIVERSAL_SKILLS_ROOT / profile,
        OPENAI_ZIP_DIR / profile,
    )
    return {
        "profile": profile,
        "top_level_count": len(top_level),
        "compiled_layer3_reference_count": len(compiled_names),
        "agent_profile_count": len(profiles),
        "zip_count": zip_count,
    }


def _preflight_static_paths(profile: str) -> None:
    """Validate every static input and managed output path before mutation."""
    source_directories = [SRC_DIR, REGISTRY_DIR, *LAYER_SOURCE_ROOTS.values()]
    source_files = [
        *(REGISTRY_DIR / spec[0] for spec in REGISTRY_SPECS.values()),
        PROFILE_SOURCE,
        HOST_ENFORCEMENT_SOURCE,
        CONTROL_PROMPT_SOURCE,
    ]

    for directory in source_directories:
        _require_within(directory, ROOT, "source directory")
        _reject_symlink_chain(directory, ROOT, "source directory")
        if not directory.is_dir() or directory.is_symlink():
            raise BuildError(f"{_display_path(directory)} must be a regular source directory")
        _reject_tree_symlinks(directory, "source tree")

    for file_path in source_files:
        _require_within(file_path, SRC_DIR, "source file")
        _reject_symlink_chain(file_path, ROOT, "source file")
        if not file_path.is_file() or file_path.is_symlink():
            raise BuildError(f"{_display_path(file_path)} must be a regular source file")

    prompt_bytes = CONTROL_PROMPT_SOURCE.read_bytes()
    try:
        prompt_text = prompt_bytes.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise BuildError("authoritative control prompt must be UTF-8") from exc
    projection_errors = prompt_projection_errors(
        prompt_text,
        CORE_CONTRACTS,
        document_bytes=prompt_bytes,
    )
    if projection_errors:
        raise BuildError(
            "authoritative control prompt projection is stale: "
            + "; ".join(projection_errors)
        )

    managed_outputs = _managed_output_paths(profile)
    _require_within(DIST_DIR, ROOT, "managed dist root")
    _reject_symlink_chain(DIST_DIR, ROOT, "managed dist root")
    if DIST_DIR.exists():
        if not DIST_DIR.is_dir() or DIST_DIR.is_symlink():
            raise BuildError(f"{_display_path(DIST_DIR)} must be a regular directory")
        _reject_tree_symlinks(DIST_DIR, "managed dist tree")
    for output in managed_outputs:
        _require_within(output, DIST_DIR, "managed output")
        _reject_symlink_chain(output, ROOT, "managed output")

    # Build inputs and managed output must never contain one another, even if a
    # test or embedding caller overrides the default roots.
    for source in [*source_directories, *source_files]:
        if _paths_overlap(source, DIST_DIR):
            raise BuildError(
                f"source/output overlap is forbidden: {_display_path(source)} and "
                f"{_display_path(DIST_DIR)}"
            )


def _managed_output_paths(profile: str) -> list[Path]:
    return [
        DIST_DIR,
        UNIVERSAL_SKILLS_ROOT / profile,
        *(root / profile for root in AGENT_SKILL_ROOTS),
        *(target for _platform, target in AGENT_PROFILE_OUTPUTS),
        OPENAI_ZIP_DIR,
        OPENAI_ZIP_DIR / profile,
    ]


def _preflight_registry_entries(
    registries: dict[str, list[dict[str, Any]]],
) -> None:
    for layer, entries in registries.items():
        source_root = LAYER_SOURCE_ROOTS[layer]
        for index, entry in enumerate(entries):
            context = f"{layer}[{index}]"
            name = _required_string(entry, "name", context)
            if not NAME_RE.fullmatch(name):
                raise BuildError(f"{context}: invalid Skill name {name!r}")
            raw_path = _required_string(entry, "path", context)
            if "\\" in raw_path:
                raise BuildError(f"{context}: path must use safe POSIX components")
            relative = PurePosixPath(raw_path)
            if relative.is_absolute() or any(
                part in {"", ".", ".."} for part in relative.parts
            ):
                raise BuildError(f"{context}: path must be a normalized repository path")

            expected = source_root / name
            try:
                expected_relative = expected.relative_to(ROOT).as_posix()
            except ValueError as exc:
                raise BuildError(f"{context}: configured layer root escapes the repository") from exc
            if relative.as_posix() != expected_relative:
                raise BuildError(
                    f"{context}: path must be the direct layer Skill root "
                    f"{expected_relative!r}"
                )

            path = ROOT.joinpath(*relative.parts)
            _require_within(path, source_root, f"{context} path")
            _reject_symlink_chain(path, ROOT, f"{context} path")
            if not path.is_dir() or path.is_symlink():
                raise BuildError(f"{context}: {_display_path(path)} must be a regular directory")
            _reject_tree_symlinks(path, f"{context} Skill tree")
            skill_file = path / "SKILL.md"
            if not skill_file.is_file() or skill_file.is_symlink():
                raise BuildError(f"{context}: {_display_path(skill_file)} must be a regular file")
            contracts = _item_reference_contracts(entry, context, name)
            for reference in contracts:
                reference_path = reference["path"]
                expected_type = reference_type_for_path(reference_path)
                if reference["type"] != expected_type:
                    raise BuildError(
                        f"{context}.reference_index: {reference_path!r} must use type "
                        f"{expected_type!r}, found {reference['type']!r}"
                    )
                target = path.joinpath(*PurePosixPath(reference_path).parts)
                _require_within(target, path, f"{context} Reference")
                _reject_symlink_chain(target, ROOT, f"{context} Reference")
                if not target.is_file() or target.is_symlink():
                    raise BuildError(
                        f"{context}: indexed Reference {_display_path(target)} must be a regular file"
                    )


def _validate_global_skill_names(items: dict[str, list[SkillItem]]) -> None:
    owners: dict[str, str] = {}
    for layer, layer_items in items.items():
        for item in layer_items:
            previous = owners.get(item.name)
            if previous is not None:
                raise BuildError(
                    f"Skill name {item.name!r} is duplicated across {previous} and {layer}"
                )
            owners[item.name] = layer


def _preflight_build_plan(
    profile: str,
    top_level: list[SkillItem],
    items: dict[str, list[SkillItem]],
    profiles: list[dict[str, Any]],
    enforcement: dict[str, Any],
) -> None:
    _validate_built_control_reference_reachability(top_level)
    layer3 = {item.name: item for item in [*items["foundation"], *items["domain"]]}
    domain_names = {item.name for item in items["domain"]}
    product_foundation_names = {
        item.name
        for item in items["foundation"]
        if item.registry.get("delivery_scope") == "product"
    }
    ownership_errors = foundation_ownership_errors(
        [item.registry for item in items["foundation"]],
        [item.registry for item in items["professional"]],
    )
    if ownership_errors:
        raise BuildError("; ".join(ownership_errors))
    for professional in items["professional"]:
        candidates = _layer3_names_for_professional(professional)
        if len(candidates) != len(_string_list(professional.registry.get("layer3_candidates"))):
            raise BuildError(f"{professional.name}: Layer 3 candidates must be unique")
        for name in candidates:
            if not NAME_RE.fullmatch(name):
                raise BuildError(f"{professional.name}: invalid Layer 3 candidate {name!r}")
            if name not in layer3:
                raise BuildError(f"{professional.name}: unknown Layer 3 candidate {name!r}")

    # Render every generated Skill into an unmanaged temporary directory and
    # run the same zip-source checks used after the build. This catches late
    # content, link-entrypoint, file-count, and size failures before dist reset.
    with tempfile.TemporaryDirectory(prefix="changeforge-build-preflight-") as raw:
        staging = Path(raw)
        for item in top_level:
            destination = staging / item.name
            _copy_skill_tree(item.path, destination)
            if item.layer == "control" and item.name == "engineering-control-plane":
                _write_compact_control_projection(destination, item)
                _copy_control_prompt(destination)
            else:
                _write_targeted_reference_contracts(destination, item)
            if item.layer == "professional":
                selected = _compiled_layer3_names(
                    profile,
                    item,
                    domain_names,
                    product_foundation_names,
                )
                if selected:
                    _write_layer3_references(destination, selected, layer3)
                _append_layer3_entrypoint(destination, profile)
                _validate_rendered_professional_body(destination / "SKILL.md")
            _validate_zip_source(destination)

    # Renderer failures are likewise configuration failures and must happen
    # before any existing Agent Profile directory is removed.
    for profile_entry in profiles:
        for platform, renderer in (
            ("codex", _render_codex_profile),
            ("claude", _render_claude_profile),
            ("copilot", _render_copilot_profile),
        ):
            rendered = renderer(profile_entry, enforcement)
            _validate_rendered_prompt_embedding(
                platform,
                profile_entry["name"],
                rendered,
            )
            _canonical_agent_profile_bytes(
                platform,
                profile_entry["name"],
                rendered,
            )


def _validate_built_control_reference_reachability(
    top_level: list[SkillItem],
) -> None:
    """Reject a registry projection that would hide a required built Reference."""

    controls = [
        item
        for item in top_level
        if item.layer == "control" and item.name == "engineering-control-plane"
    ]
    if len(controls) != 1:
        raise BuildError(
            "build must contain exactly one engineering-control-plane Skill"
        )
    contracts = _item_reference_contracts(
        controls[0].registry,
        controls[0].name,
        controls[0].name,
    )
    actual = [str(contract["path"]) for contract in contracts]
    expected = list(
        CORE_CONTRACTS["reference_contract"]["control_required_by"]
    )
    if actual != expected:
        raise BuildError(
            "control Reference registry must exactly expose the Core Model paths; "
            "otherwise a required Reference would be unreachable after build"
        )


def _validate_rendered_professional_body(skill_file: Path) -> None:
    """Reject a Professional root whose generated delivery exceeds the hard gate."""
    try:
        _metadata, _raw_frontmatter, body = parse_frontmatter(skill_file)
    except ValidationProblem as exc:
        raise BuildError(str(exc).replace(str(ROOT) + "/", "")) from exc
    line_count = len(body.splitlines())
    if line_count > MAX_RENDERED_PROFESSIONAL_BODY_LINES:
        raise BuildError(
            f"{_display_path(skill_file)}: rendered Professional SKILL.md body has "
            f"{line_count} lines; maximum is {MAX_RENDERED_PROFESSIONAL_BODY_LINES}"
        )


def _require_within(path: Path, root: Path, label: str) -> None:
    path_absolute = path.expanduser().absolute()
    root_absolute = root.expanduser().absolute()
    try:
        path_absolute.relative_to(root_absolute)
    except ValueError as exc:
        raise BuildError(
            f"{label} {_display_path(path)} must remain under {_display_path(root)}"
        ) from exc


def _reject_symlink_chain(path: Path, root: Path, label: str) -> None:
    path_absolute = path.expanduser().absolute()
    root_absolute = root.expanduser().absolute()
    try:
        relative = path_absolute.relative_to(root_absolute)
    except ValueError as exc:
        raise BuildError(f"{label} {_display_path(path)} escapes the repository") from exc
    cursor = root_absolute
    if cursor.is_symlink():
        raise BuildError(f"{label} {_display_path(cursor)} must not be a symlink")
    for part in relative.parts:
        cursor = cursor / part
        if cursor.is_symlink():
            raise BuildError(f"{label} {_display_path(cursor)} must not be a symlink")


def _reject_tree_symlinks(root: Path, label: str) -> None:
    for path in sorted(root.rglob("*")):
        if path.is_symlink():
            raise BuildError(f"{label} {_display_path(path)} must not be a symlink")


def _paths_overlap(left: Path, right: Path) -> bool:
    left_resolved = left.resolve(strict=False)
    right_resolved = right.resolve(strict=False)
    return (
        left_resolved == right_resolved
        or left_resolved in right_resolved.parents
        or right_resolved in left_resolved.parents
    )


def _display_path(path: Path) -> str:
    try:
        return path.expanduser().absolute().relative_to(ROOT.expanduser().absolute()).as_posix()
    except ValueError:
        return str(path)


def _load_registries() -> dict[str, list[dict[str, Any]]]:
    registries: dict[str, list[dict[str, Any]]] = {}
    for layer, (file_name, expected_kind, key) in REGISTRY_SPECS.items():
        path = REGISTRY_DIR / file_name
        if not path.is_file():
            raise BuildError(f"missing registry: {path.relative_to(ROOT)}")
        data = load_yaml_file(path)
        expected_schema_version = REGISTRY_SCHEMA_VERSIONS[layer]
        if (
            not isinstance(data, dict)
            or data.get("schema_version") != expected_schema_version
            or data.get("kind") != expected_kind
        ):
            raise BuildError(
                f"{path.relative_to(ROOT)} must use schema_version "
                f"{expected_schema_version} and kind {expected_kind}"
            )
        entries = data.get(key)
        if not isinstance(entries, list):
            raise BuildError(f"{path.relative_to(ROOT)}:{key} must be a list")
        normalized: list[dict[str, Any]] = []
        for index, entry in enumerate(entries):
            if not isinstance(entry, dict):
                raise BuildError(f"{file_name}:{key}[{index}] must be a mapping")
            required_fields = REQUIRED_REGISTRY_FIELDS
            if layer != "control":
                required_fields = (*required_fields, "required_expertise_tags")
            if layer == "foundation":
                required_fields = (*required_fields, "delivery_scope", "content_class")
            for field in required_fields:
                if field not in entry:
                    raise BuildError(f"{file_name}:{key}[{index}] missing {field}")
            if layer == "professional":
                _validate_role_contract_maps(entry, f"{file_name}:{key}[{index}]")
            if layer != "control":
                expertise_errors = required_expertise_tag_errors(
                    entry.get("required_expertise_tags"),
                    f"{file_name}:{key}[{index}]",
                    layer=layer,
                    skill_name=entry.get("name"),
                    foundation_group=entry.get("group"),
                )
                if expertise_errors:
                    raise BuildError("; ".join(expertise_errors))
            if layer == "foundation":
                context = f"{file_name}:{key}[{index}]"
                class_errors = [
                    *foundation_registry_field_errors(entry, context),
                    *foundation_content_class_errors(entry, context),
                ]
                if class_errors:
                    raise BuildError("; ".join(class_errors))
            normalized.append(entry)
        registries[layer] = normalized
    return registries


def _validate_role_contract_maps(entry: dict[str, Any], context: str) -> None:
    roles = _string_list(entry.get("role_support"))
    errors = [
        *role_contract_map_errors(entry.get("required_inputs_by_role"), roles, f"{context}.required_inputs_by_role"),
        *role_contract_map_errors(entry.get("output_contract_by_role"), roles, f"{context}.output_contract_by_role"),
    ]
    if errors:
        raise BuildError("; ".join(errors))


def _load_items(layer: str, entries: list[dict[str, Any]]) -> list[SkillItem]:
    items: list[SkillItem] = []
    seen: set[str] = set()
    for index, entry in enumerate(entries):
        name = _required_string(entry, "name", f"{layer}[{index}]")
        rel_path = _required_string(entry, "path", f"{layer}[{index}]")
        if name in seen:
            raise BuildError(f"duplicate {layer} Skill: {name}")
        seen.add(name)
        path = ROOT / rel_path
        skill_file = path / "SKILL.md"
        if not skill_file.is_file():
            raise BuildError(f"{rel_path} is missing SKILL.md")
        try:
            metadata, _raw, body = parse_frontmatter(skill_file)
        except ValidationProblem as exc:
            raise BuildError(str(exc).replace(str(ROOT) + "/", "")) from exc
        if metadata.get("name") != name:
            raise BuildError(f"{skill_file.relative_to(ROOT)} name does not match registry")
        description = metadata.get("description")
        if not isinstance(description, str) or not description.strip():
            raise BuildError(f"{skill_file.relative_to(ROOT)} is missing description")
        items.append(
            SkillItem(
                name=name,
                path=path,
                layer=layer,
                description=description.strip(),
                metadata=metadata,
                body=body,
                registry=dict(entry),
            )
        )
    return items


def _required_string(entry: dict[str, Any], field: str, context: str) -> str:
    value = entry.get(field)
    if not isinstance(value, str) or not value.strip():
        raise BuildError(f"{context}: {field} must be a non-empty string")
    return value.strip()


def _top_level_items(
    profile: str,
    items: dict[str, list[SkillItem]],
) -> list[SkillItem]:
    if profile == "recommended":
        return [*items["control"], *items["professional"]]
    if profile == "full":
        return [*items["control"], *items["professional"], *items["domain"]]
    if profile == "dev":
        return [
            *items["control"],
            *items["professional"],
            *items["foundation"],
            *items["domain"],
        ]
    raise BuildError(f"unsupported profile: {profile}")


def _build_skill_roots(
    profile: str,
    top_level: list[SkillItem],
    items: dict[str, list[SkillItem]],
    profiles: list[dict[str, Any]],
    enforcement: dict[str, Any],
    source_snapshot: dict[str, object],
) -> set[str]:
    layer3 = {
        item.name: item for item in [*items["foundation"], *items["domain"]]
    }
    domain_names = {item.name for item in items["domain"]}
    product_foundation_names = {
        item.name
        for item in items["foundation"]
        if item.registry.get("delivery_scope") == "product"
    }
    all_compiled: set[str] = set()
    for root in (UNIVERSAL_SKILLS_ROOT, *AGENT_SKILL_ROOTS):
        profile_root = root / profile
        _reset_dir(profile_root)
        compiled_by_skill: dict[str, list[str]] = {}
        for item in top_level:
            destination = profile_root / item.name
            _copy_skill_tree(item.path, destination)
            if item.layer == "control" and item.name == "engineering-control-plane":
                _write_compact_control_projection(destination, item)
                _copy_control_prompt(destination)
            else:
                _write_targeted_reference_contracts(destination, item)
            if item.layer == "professional":
                selected = _compiled_layer3_names(
                    profile,
                    item,
                    domain_names,
                    product_foundation_names,
                )
                compiled = (
                    _write_layer3_references(destination, selected, layer3)
                    if selected
                    else []
                )
                _append_layer3_entrypoint(destination, profile)
                compiled_by_skill[item.name] = compiled
                all_compiled.update(compiled)
        _write_build_manifest(
            profile_root,
            profile,
            top_level,
            items,
            compiled_by_skill,
            profiles,
            enforcement,
            source_snapshot,
        )
    return all_compiled


def _layer3_names_for_professional(
    professional: SkillItem,
) -> list[str]:
    return list(dict.fromkeys(_string_list(professional.registry.get("layer3_candidates"))))


def _compiled_layer3_names(
    profile: str,
    professional: SkillItem,
    domain_names: set[str],
    product_foundation_names: set[str],
) -> list[str]:
    allowed = domain_names | product_foundation_names
    candidates = [
        name
        for name in _layer3_names_for_professional(professional)
        if name in allowed
    ]
    if profile == "recommended":
        return candidates
    if profile == "full":
        return [name for name in candidates if name not in domain_names]
    if profile == "dev":
        return []
    raise BuildError(f"unsupported profile: {profile}")


def _copy_control_prompt(destination: Path) -> None:
    if not CONTROL_PROMPT_SOURCE.is_file():
        raise BuildError(f"missing {CONTROL_PROMPT_SOURCE.relative_to(ROOT)}")
    references = destination / "references"
    references.mkdir(parents=True, exist_ok=True)
    shutil.copy2(CONTROL_PROMPT_SOURCE, references / "main-control-agent.md")
    runtime_metadata = CORE_CONTRACTS["execution_level_contract"]["projection"][
        "runtime_reference"
    ]
    runtime_source = ROOT / runtime_metadata["path"]
    runtime_target = references / PurePosixPath(runtime_metadata["path"]).name
    if not runtime_source.is_file() or not runtime_target.is_file():
        raise BuildError("missing execution-level runtime Reference")
    if runtime_target.read_bytes() != runtime_source.read_bytes():
        raise BuildError("built execution-level runtime Reference is not an exact source copy")
    runtime_errors = execution_level_runtime_reference_errors(
        runtime_target.read_text(encoding="utf-8")
    )
    if runtime_errors:
        raise BuildError("; ".join(runtime_errors))


def _write_layer3_references(
    destination: Path,
    selected_names: list[str],
    layer3: dict[str, SkillItem],
) -> list[str]:
    root = destination / "references" / "layer3"
    if root.exists():
        shutil.rmtree(root)
    root.mkdir(parents=True, exist_ok=True)
    compiled: list[str] = []
    index = [
        GENERATED_MARKER,
        "",
        "# Layer 3 Reference Index",
        "",
        "Discovery and build-validation index only. During task execution, open",
        "the exact `references/layer3/<name>.md` file named by the capsule directly.",
        "Do not read this index first or preload it as a catalog.",
        "",
    ]
    for name in selected_names:
        item = layer3.get(name)
        if item is None:
            raise BuildError(f"unknown Layer 3 candidate {name!r}")
        compiled.append(name)
        target = root / f"{name}.md"
        target.write_text(
            _render_layer3_reference(item),
            encoding="utf-8",
        )
        _copy_layer3_assets(item, root / name)
        index.extend([f"- [{name}]({name}.md)"])
    if not compiled:
        index.append("No Layer 3 candidates are assigned to this Skill.")
    index.append("")
    (root / "index.md").write_text("\n".join(index), encoding="utf-8")
    return compiled


def _append_layer3_entrypoint(destination: Path, profile: str) -> None:
    """Describe only the current build's Layer 3 delivery at the Skill root."""
    skill_file = destination / "SKILL.md"
    if not skill_file.is_file():
        raise BuildError(f"{destination.relative_to(ROOT)} is missing root SKILL.md")
    source = skill_file.read_text(encoding="utf-8").rstrip()
    compiled_index = destination / "references" / "layer3" / "index.md"
    if profile == "recommended":
        delivery = [
            "This build compiles assigned Foundation and Domain guidance into this",
            "Professional Skill's `references/layer3/` directory.",
        ]
    elif profile == "full":
        delivery = [
            "This build compiles assigned Foundation guidance into this Professional",
            "Skill's `references/layer3/` directory and delivers Domain guidance as",
            "top-level Skills.",
        ]
    elif profile == "dev":
        delivery = [
            "This build delivers assigned Foundation and Domain guidance as top-level",
            "Skills; it does not compile Layer 3 references into this Professional Skill.",
        ]
    else:
        raise BuildError(f"unsupported profile: {profile}")
    if compiled_index.is_file():
        delivery.extend(
            [
                "Open each capsule-named compiled item directly at",
                "`references/layer3/<name>.md`. Never preload Layer 3 or open the",
                "[Layer 3 index](references/layer3/index.md) during task execution. The",
                "index exists only for build validation and human discovery.",
            ]
        )
    elif profile == "recommended":
        delivery.extend(
            [
                "This Skill has no assigned compiled Layer 3 guidance. Never preload Layer 3",
                "or open a Layer 3 index or catalog.",
            ]
        )
    if profile == "full":
        delivery.extend(
            [
                "Load each capsule-named Domain item as a top-level Skill.",
                "Never preload Layer 3 or open a Layer 3 index or catalog.",
            ]
        )
    elif profile == "dev":
        delivery.extend(
            [
                "Load each capsule-named Foundation or Domain item as a top-level Skill.",
                "Never preload Layer 3 or open a Layer 3 index or catalog.",
            ]
        )
    entrypoint = "\n".join(
        [
            GENERATED_MARKER,
            "",
            "## Layer 3 Delivery",
            "",
            *delivery,
        ]
    )
    skill_file.write_text(f"{source}\n\n{entrypoint}\n", encoding="utf-8")


def _render_layer3_reference(item: SkillItem) -> str:
    body = _render_targeted_reference_section(
        item.body.strip(),
        _item_reference_contracts(item.registry, item.name, item.name),
        item.name,
    )
    body = _project_layer3_reference(item, body)
    body = _rewrite_layer3_links(body, item.name)
    return "\n".join(
        [
            GENERATED_MARKER,
            "",
            f"<!-- Layer: {item.layer}; source: {item.path.relative_to(ROOT)} -->",
            "",
            body,
            "",
        ]
    )


def _markdown_heading_sections(markdown: str) -> tuple[list[str], dict[str, list[str]]]:
    """Return unfenced H1 titles and complete H2 bodies without truncation."""

    lines = markdown.splitlines()
    h1_titles: list[str] = []
    h2_rows: list[tuple[int, str]] = []
    in_fence = False
    fence_marker: str | None = None
    for index, line in enumerate(lines):
        stripped = line.strip()
        fence_match = re.match(r"^(```+|~~~+)", stripped)
        if fence_match:
            marker = fence_match.group(1)
            if not in_fence:
                in_fence = True
                fence_marker = marker[:3]
            elif fence_marker and marker.startswith(fence_marker):
                in_fence = False
                fence_marker = None
            continue
        if in_fence:
            continue
        h1_match = re.match(r"^#(?!#)[ \t]+(.+?)[ \t]*$", line)
        if h1_match:
            h1_titles.append(h1_match.group(1).strip())
            continue
        h2_match = re.match(r"^##(?!#)[ \t]+(.+?)[ \t]*$", line)
        if h2_match:
            h2_rows.append((index, h2_match.group(1).strip()))

    sections: dict[str, list[str]] = {}
    for position, (line_index, title) in enumerate(h2_rows):
        end_index = h2_rows[position + 1][0] if position + 1 < len(h2_rows) else len(lines)
        sections.setdefault(title, []).append(
            "\n".join(lines[line_index + 1 : end_index]).strip()
        )
    return h1_titles, sections


def _project_layer3_reference(item: SkillItem, markdown: str) -> str:
    """Project an authoring root into the exact AI-consumption section contract."""

    section_contract = LAYER3_PROJECTION_SECTIONS.get(item.layer)
    if section_contract is None:
        raise BuildError(
            f"{item.name}: AI-consumption projection does not support layer {item.layer!r}"
        )
    h1_titles, sections = _markdown_heading_sections(markdown)
    if h1_titles != [item.name]:
        raise BuildError(
            f"{item.name}: expected exactly one H1 title matching the Skill name, "
            f"found {h1_titles}"
        )

    output = [f"# {item.name}"]
    for source_heading, projected_heading in section_contract:
        values = sections.get(source_heading, [])
        if len(values) != 1 or not values[0]:
            raise BuildError(
                f"{item.name}: AI-consumption projection requires exactly one non-empty "
                f"{source_heading!r} section, found {len(values)}"
            )
        output.extend(["", f"## {projected_heading}", "", values[0]])

    projected = "\n".join(output).rstrip() + "\n"
    _projected_h1, projected_sections = _markdown_heading_sections(projected)
    projected_headings = list(projected_sections)
    expected_headings = [target for _source, target in section_contract]
    if projected_headings != expected_headings:
        raise BuildError(
            f"{item.name}: projected headings {projected_headings} do not match "
            f"{expected_headings}"
        )
    forbidden = sorted(
        set(projected_headings) & LAYER3_PROJECTION_FORBIDDEN_HEADINGS
    )
    if forbidden:
        raise BuildError(
            f"{item.name}: projected Layer 3 reference contains forbidden headings {forbidden}"
        )
    return projected


def _item_reference_contracts(
    entry: dict[str, Any], context: str, owner: str
) -> list[dict[str, str | list[str]]]:
    try:
        return reference_contracts(
            entry.get("reference_index"),
            f"{context}.reference_index",
            owner=owner,
        )
    except ValidationProblem as exc:
        raise BuildError(str(exc)) from exc


def _write_targeted_reference_contracts(destination: Path, item: SkillItem) -> None:
    skill_file = destination / "SKILL.md"
    if not skill_file.is_file():
        raise BuildError(f"{_display_path(destination)} is missing root SKILL.md")
    source = skill_file.read_text(encoding="utf-8")
    rendered = _render_targeted_reference_section(
        source,
        _item_reference_contracts(item.registry, item.name, item.name),
        item.name,
    )
    skill_file.write_text(rendered, encoding="utf-8")


def _write_compact_control_projection(destination: Path, item: SkillItem) -> None:
    """Emit the built-only Control router directly from Reference Contract v2."""

    skill_file = destination / "SKILL.md"
    try:
        _metadata, raw_frontmatter, _body = parse_frontmatter(skill_file)
    except ValidationProblem as exc:
        raise BuildError(str(exc)) from exc
    contracts = _item_reference_contracts(item.registry, item.name, item.name)
    rows: list[list[str]] = []
    for contract in contracts:
        path = str(contract["path"])
        label = PurePosixPath(path).stem.removesuffix("-template").split("-")[-1]
        rows.append(
            [
                f"[{label}]({path})",
                str(contract["type"]),
                str(contract["load_when"]),
                str(contract["do_not_load_when"]),
                ", ".join(contract["required_by"]),
                ", ".join(contract["required_output"]),
            ]
        )
    try:
        table = render_compact_markdown_table(
            TARGETED_REFERENCE_TABLE_COLUMNS,
            rows,
            f"{item.name}.reference_index",
        )
    except ValidationProblem as exc:
        raise BuildError(str(exc)) from exc
    table = "\n".join(
        re.sub(r"\s*\|\s*", "|", line) if line.startswith("|") else line
        for line in table.splitlines()
    )
    rendered = "\n".join(
        [
            "---",
            raw_frontmatter,
            "---",
            "",
            "# Engineering Control Plane",
            "",
            "Reference Contract v2; Prompt owns rules.",
            "No Profile: load [Prompt](references/main-control-agent.md).",
            "",
            "## Targeted References",
            "",
            *table.splitlines(),
            "",
        ]
    )
    skill_file.write_text(rendered, encoding="utf-8")


def _render_targeted_reference_section(
    markdown: str,
    contracts: list[dict[str, str | list[str]]],
    owner: str,
) -> str:
    try:
        return render_targeted_reference_section(markdown, contracts, owner)
    except ValidationProblem as exc:
        raise BuildError(str(exc)) from exc


def _rewrite_layer3_links(body: str, name: str) -> str:
    body = re.sub(
        r"(?P<prefix>\]\()(?P<target>(?:\./)?references/[^)\s]+)(?P<suffix>\))",
        lambda match: (
            f"{match.group('prefix')}{name}/{match.group('target').removeprefix('./')}"
            f"{match.group('suffix')}"
        ),
        body,
    )
    body = re.sub(
        r"(?P<prefix>\]\()(?P<target>(?:\./)?examples/[^)\s]+)(?P<suffix>\))",
        lambda match: (
            f"{match.group('prefix')}{name}/{match.group('target').removeprefix('./')}"
            f"{match.group('suffix')}"
        ),
        body,
    )
    body = re.sub(
        r"`(?P<target>(?:\./)?(?:references|examples|assets)/[^`\s]+)`",
        lambda match: (
            f"`{name}/{match.group('target').removeprefix('./')}`"
        ),
        body,
    )
    return body


def _copy_layer3_assets(item: SkillItem, destination: Path) -> None:
    for directory in ("references", "examples", "assets"):
        source = item.path / directory
        if source.is_dir():
            shutil.copytree(source, destination / directory)


def _load_agent_profiles() -> list[dict[str, Any]]:
    if not PROFILE_SOURCE.is_file():
        raise BuildError(f"missing {PROFILE_SOURCE.relative_to(ROOT)}")
    try:
        data = json.loads(PROFILE_SOURCE.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise BuildError(f"invalid Agent Profile JSON: {exc}") from exc
    if not isinstance(data, dict) or data.get("schema_version") != 1:
        raise BuildError("Agent Profiles must use schema_version 1")
    profiles = data.get("profiles")
    if not isinstance(profiles, list):
        raise BuildError("Agent Profiles must contain a profiles list")
    normalized: list[dict[str, Any]] = []
    seen: set[str] = set()
    for profile in profiles:
        if not isinstance(profile, dict):
            raise BuildError("Agent Profile entry must be a mapping")
        name = str(profile.get("name") or "").strip()
        if not NAME_RE.fullmatch(name) or name in seen:
            raise BuildError(f"invalid or duplicate Agent Profile name: {name!r}")
        seen.add(name)
        role_contract = ROLE_CONTRACT_MODEL.get(name)
        if role_contract is None:
            raise BuildError(f"unknown Agent Profile role: {name!r}")
        expected_fields = set(PROFILE_CONTRACT_MODEL["profile_fields"]) | set(
            PROFILE_CONTRACT_MODEL["optional_fields_by_role"][name]
        )
        if set(profile) != expected_fields:
            raise BuildError(f"{name}: fields do not match profile_contract")
        tools = _string_list(profile.get("tools"))
        if tools != role_contract["tools"]:
            raise BuildError(f"{name}: tools do not match the core role contract")
        if profile.get("sandbox") != role_contract["sandbox"]:
            raise BuildError(f"{name}: sandbox does not match the core role contract")
        prompt_path = profile.get("prompt")
        if prompt_path is not None:
            if name != "main-control-agent" or prompt_path != CONTROL_PROMPT_SOURCE.relative_to(ROOT).as_posix():
                raise BuildError(
                    f"{name}: profile prompt must be the authoritative main control prompt"
                )
            _reject_symlink_chain(CONTROL_PROMPT_SOURCE, ROOT, f"{name} prompt")
            if not CONTROL_PROMPT_SOURCE.is_file() or CONTROL_PROMPT_SOURCE.is_symlink():
                raise BuildError(f"{name}: control prompt must be a regular file")
        normalized.append(dict(profile))
    if set(seen) != set(ROLE_CONTRACT_MODEL):
        raise BuildError("Agent Profiles must contain exactly the four static roles")
    return normalized


def _normalized_decision_capabilities(entry: dict[str, Any]) -> dict[str, str]:
    """Project adapter metadata to generic capability facts."""

    profile_supported = entry.get("profile_delivery") in ENFORCEMENT_STATUSES[:-1]
    diff_supported = entry.get("diff_input_mode") in {"native", "supplied-artifact"}
    validation_supported = entry.get("validation_mode") in {
        "native-read-only",
        "task-no-edit",
    }
    observation_supported = entry.get("utility_no_edit") in ENFORCEMENT_STATUSES[:-1]
    supported = "supported"
    unsupported = "unsupported"
    return {
        "bounded-source-read": supported if profile_supported else unsupported,
        "workspace-mutation": supported if profile_supported else unsupported,
        "non-mutating-validation": supported if validation_supported else unsupported,
        "exact-change-evidence-read": supported if diff_supported else unsupported,
        "exact-change-evidence-export": supported if diff_supported else unsupported,
        "reviewer-accessible-change-reference": supported if diff_supported else unsupported,
        "workspace-state-observation": supported if observation_supported else unsupported,
    }


def _render_decision_capability_facts(capabilities: dict[str, str]) -> str:
    groups = {
        state: [
            field
            for field in DECISION_CAPABILITY_FIELDS
            if capabilities[field] == state
        ]
        for state in DECISION_CAPABILITY_STATES
    }
    return (
        "Current capability facts: supported "
        + ("/".join(groups["supported"]) or "none")
        + "; unsupported "
        + ("/".join(groups["unsupported"]) or "none")
        + "."
    )


def _load_host_enforcement() -> dict[str, Any]:
    if not HOST_ENFORCEMENT_SOURCE.is_file():
        raise BuildError(f"missing {HOST_ENFORCEMENT_SOURCE.relative_to(ROOT)}")
    try:
        data = json.loads(HOST_ENFORCEMENT_SOURCE.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise BuildError(f"invalid host enforcement JSON: {exc}") from exc
    if not isinstance(data, dict) or data.get("schema_version") != 4:
        raise BuildError("host enforcement matrix must use schema_version 4")
    if set(data) != {
        "schema_version",
        "source_summary",
        "status_values",
        "mode_values",
        "hosts",
    }:
        raise BuildError("host enforcement matrix fields must match schema v4")
    if tuple(data.get("status_values") or ()) != ENFORCEMENT_STATUSES:
        raise BuildError("host enforcement status_values must match the fixed status enum")
    if not isinstance(data.get("source_summary"), str) or not data["source_summary"].strip():
        raise BuildError("host enforcement matrix requires source_summary")
    if data.get("mode_values") != {
        field: list(values) for field, values in HOST_MODE_VALUES.items()
    }:
        raise BuildError("host enforcement mode_values must match the adapter contract")
    hosts = data.get("hosts")
    if not isinstance(hosts, dict) or set(hosts) != set(ENFORCEMENT_HOSTS):
        raise BuildError("host enforcement matrix must contain exactly the supported hosts")
    expected_roles = set(ROLE_CONTRACT_MODEL)
    for host, entry in hosts.items():
        expected_fields = {
            *HOST_ENFORCEMENT_CAPABILITIES,
            "diff_input_mode",
            "validation_mode",
            "native_diff_safeguards",
            "roles",
        }
        if not isinstance(entry, dict) or set(entry) != expected_fields:
            raise BuildError(f"{host}: host enforcement fields must match schema v4")
        for capability in HOST_ENFORCEMENT_CAPABILITIES:
            if entry.get(capability) not in ENFORCEMENT_STATUSES:
                raise BuildError(f"{host}: invalid {capability} enforcement")
        diff_input_mode = entry.get("diff_input_mode")
        validation_mode = entry.get("validation_mode")
        utility_no_edit = entry.get("utility_no_edit")
        if diff_input_mode not in HOST_MODE_VALUES["diff_input_mode"]:
            raise BuildError(f"{host}: invalid diff_input_mode")
        if validation_mode not in HOST_MODE_VALUES["validation_mode"]:
            raise BuildError(f"{host}: invalid validation_mode")
        if tuple(_normalized_decision_capabilities(entry)) != DECISION_CAPABILITY_FIELDS:
            raise BuildError(f"{host}: normalized decision capabilities drift from Core")
        if utility_no_edit not in ENFORCEMENT_STATUSES:
            raise BuildError(f"{host}: invalid utility_no_edit enforcement")
        safeguards = entry.get("native_diff_safeguards")
        expected_safeguards = list(NATIVE_DIFF_SAFEGUARDS) if diff_input_mode == "native" else []
        if safeguards != expected_safeguards:
            raise BuildError(f"{host}: native diff safeguards do not match adapter mode")
        roles = entry.get("roles")
        if not isinstance(roles, dict) or set(roles) != expected_roles:
            raise BuildError(f"{host}: enforcement roles must be the four static profiles")
        for role, role_entry in roles.items():
            if not isinstance(role_entry, dict):
                raise BuildError(f"{host}:{role}: enforcement entry must be an object")
            expected_role_fields = {
                *ENFORCEMENT_CAPABILITIES,
                "rendered_tools",
                "limitations",
            }
            if set(role_entry) != expected_role_fields:
                raise BuildError(
                    f"{host}:{role}: enforcement fields must match schema v3"
                )
            for capability in ENFORCEMENT_CAPABILITIES:
                if role_entry.get(capability) not in ENFORCEMENT_STATUSES:
                    raise BuildError(
                        f"{host}:{role}: invalid {capability} enforcement status"
                    )
            rendered = role_entry.get("rendered_tools")
            limitations = role_entry.get("limitations")
            if not isinstance(rendered, list) or any(
                not isinstance(tool, str) or not tool for tool in rendered
            ):
                raise BuildError(f"{host}:{role}: rendered_tools must be a string list")
            if not isinstance(limitations, list) or any(
                not isinstance(item, str) or not item.strip() for item in limitations
            ):
                raise BuildError(f"{host}:{role}: limitations must be a string list")
    if hosts["codex"]["roles"]["main-control-agent"]["tool_allowlist"] != "prompt-enforced":
        raise BuildError("Codex main-control-agent tool allowlist must be prompt-enforced")
    for host, expected_mode in EXTERNAL_READ_HOST_MODES.items():
        roles = hosts[host]["roles"]
        if roles["analysis-agent"]["external_source_read"] != expected_mode:
            raise BuildError(
                f"{host}:analysis-agent external_source_read must be {expected_mode}"
            )
        for role in set(ROLE_CONTRACT_MODEL) - {"analysis-agent"}:
            if roles[role]["external_source_read"] != "unsupported":
                raise BuildError(
                    f"{host}:{role} external_source_read must be unsupported"
                )
    if hosts["claude"]["roles"]["analysis-agent"]["rendered_tools"] != [
        "Skill",
        "Read",
        "Grep",
        "Glob",
        "WebSearch",
        "WebFetch",
    ]:
        raise BuildError(
            "claude:analysis-agent must expose only the native read and Web read tools"
        )
    for host in ("claude", "copilot"):
        review = hosts[host]["roles"]["review-agent"]
        if review["read_only_command_semantics"] != "unsupported":
            raise BuildError(f"{host}: review read-only command semantics must be unsupported")
        if set(review["rendered_tools"]) & {"Bash", "execute"}:
            raise BuildError(f"{host}: review cannot receive a mutable command tool")
    return data


def _build_agent_profiles(
    profiles: list[dict[str, Any]], enforcement: dict[str, Any]
) -> None:
    for platform, target in AGENT_PROFILE_OUTPUTS:
        _reset_dir(target)
        for profile in profiles:
            suffix = {
                "codex": ".toml",
                "claude": ".md",
                "copilot": ".agent.md",
            }[platform]
            renderer = {
                "codex": _render_codex_profile,
                "claude": _render_claude_profile,
                "copilot": _render_copilot_profile,
            }[platform]
            rendered = renderer(profile, enforcement)
            _validate_rendered_prompt_embedding(platform, profile["name"], rendered)
            (target / f"{profile['name']}{suffix}").write_bytes(
                _canonical_agent_profile_bytes(
                    platform,
                    profile["name"],
                    rendered,
                )
            )


def _canonical_agent_profile_bytes(
    platform: str,
    role: str,
    rendered: str,
) -> bytes:
    payload = rendered.encode("utf-8")
    if b"\r" in payload:
        raise BuildError(f"{platform}:{role}: rendered Profile must use canonical LF bytes")
    return payload


def _agent_profile_digests(
    profiles: list[dict[str, Any]], enforcement: dict[str, Any]
) -> dict[str, dict[str, str]]:
    renderers = {
        "codex": _render_codex_profile,
        "claude": _render_claude_profile,
        "copilot": _render_copilot_profile,
    }
    return {
        host: {
            profile["name"]: hashlib.sha256(
                _canonical_agent_profile_bytes(
                    host,
                    profile["name"],
                    renderer(profile, enforcement),
                )
            ).hexdigest()
            for profile in profiles
        }
        for host, renderer in renderers.items()
    }


def _profile_instructions(
    profile: dict[str, Any],
    host: str | None = None,
    enforcement: dict[str, Any] | None = None,
) -> str:
    instructions = str(profile.get("instructions") or "").strip()
    prompt_path = profile.get("prompt")
    if isinstance(prompt_path, str) and prompt_path:
        path = ROOT / prompt_path
        if not path.is_file():
            raise BuildError(f"missing profile prompt {prompt_path}")
        instructions = f"{instructions}\n\n{path.read_text(encoding='utf-8').strip()}"
    tools = ", ".join(_string_list(profile.get("tools")))
    capability_projection = ""
    if host is not None and profile.get("name") == "main-control-agent":
        matrix = enforcement or _load_host_enforcement()
        host_entry = matrix["hosts"][host]
        capability_facts = _normalized_decision_capabilities(host_entry)
        capability_projection = "\n\n" + _render_decision_capability_facts(capability_facts)
    elif host is not None and profile.get("name") == "analysis-agent":
        matrix = enforcement or _load_host_enforcement()
        mode = matrix["hosts"][host]["roles"]["analysis-agent"][
            "external_source_read"
        ]
        capability_projection = (
            "\n\nCurrent external-read mode: "
            f"external_source_read={mode}."
        )
    return f"{instructions}\n\nDeclared tool boundary: {tools}.{capability_projection}"


def _validate_rendered_prompt_embedding(
    platform: str,
    role: str,
    rendered: str,
) -> None:
    """Require one decoded canonical Prompt in Main and none in workers."""

    surface = rendered
    if platform == "codex":
        try:
            document = tomllib.loads(rendered)
        except tomllib.TOMLDecodeError as exc:
            raise BuildError(f"codex:{role}: rendered Profile is invalid TOML") from exc
        surface = document.get("developer_instructions")
        if not isinstance(surface, str):
            raise BuildError(
                f"codex:{role}: developer_instructions must be a TOML string"
            )
    canonical_prompt = CONTROL_PROMPT_SOURCE.read_text(encoding="utf-8").strip()
    count = surface.count(canonical_prompt)
    if role == "main-control-agent" and count != 1:
        raise BuildError(
            f"{platform}:{role}: canonical control prompt must be embedded exactly once"
        )
    if role != "main-control-agent" and count != 0:
        raise BuildError(f"{platform}:{role}: worker must not embed the control prompt")


def _render_codex_profile(
    profile: dict[str, Any], enforcement: dict[str, Any] | None = None
) -> str:
    sandbox = "workspace-write" if profile.get("sandbox") == "workspace-write" else "read-only"
    instructions = _profile_instructions(profile, "codex", enforcement)
    if "'''" in instructions:
        raise BuildError(
            f"codex:{profile['name']}: instructions cannot use a TOML literal delimiter"
        )
    return (
        f"name = {json.dumps(profile['name'])}\n"
        f"description = {json.dumps(profile['description'])}\n"
        f"sandbox_mode = {json.dumps(sandbox)}\n"
        "developer_instructions = '''\n"
        f"{instructions}'''\n"
    )


def _render_claude_profile(
    profile: dict[str, Any], enforcement: dict[str, Any] | None = None
) -> str:
    # Claude's explicit tools field is an allowlist. Skill is required to load
    # the named Control/Professional guidance and does not grant target-repo I/O.
    matrix = enforcement or _load_host_enforcement()
    tools = matrix["hosts"]["claude"]["roles"][profile["name"]]["rendered_tools"]
    return (
        "---\n"
        f"name: {profile['name']}\n"
        f"description: {profile['description']}\n"
        f"tools: {', '.join(dict.fromkeys(tools)) or '[]'}\n"
        "---\n\n"
        f"{_profile_instructions(profile, 'claude', matrix)}\n"
    )


def _render_copilot_profile(
    profile: dict[str, Any], enforcement: dict[str, Any] | None = None
) -> str:
    matrix = enforcement or _load_host_enforcement()
    tools = matrix["hosts"]["copilot"]["roles"][profile["name"]]["rendered_tools"]
    rendered = ", ".join(json.dumps(tool) for tool in dict.fromkeys(tools))
    model_invocation = (
        "disable-model-invocation: true\n"
        if profile["name"] == "main-control-agent"
        else ""
    )
    return (
        "---\n"
        f"name: {profile['name']}\n"
        f"description: {profile['description']}\n"
        f"{model_invocation}"
        "user-invocable: true\n"
        f"tools: [{rendered}]\n"
        "---\n\n"
        f"{_profile_instructions(profile, 'copilot', matrix)}\n"
    )


def _write_build_manifest(
    profile_root: Path,
    profile: str,
    top_level: list[SkillItem],
    items: dict[str, list[SkillItem]],
    compiled_by_skill: dict[str, list[str]],
    profiles: list[dict[str, Any]],
    enforcement: dict[str, Any],
    source_snapshot: dict[str, object],
) -> None:
    foundation_names = {item.name for item in items["foundation"]}
    compiled_foundation_skills = sorted(
        {
            candidate
            for candidates in compiled_by_skill.values()
            for candidate in candidates
            if candidate in foundation_names
        }
    )
    manifest = {
        "architecture": "hookless-control-plane-v1",
        "profile": profile,
        "source_version": _source_version(),
        "authoritative_build_inputs": source_snapshot,
        "top_level_skills": [item.name for item in top_level],
        "control_skills": [item.name for item in items["control"]],
        "professional_skills": [item.name for item in items["professional"]],
        "foundation_skills": [item.name for item in items["foundation"]],
        "foundation_delivery_scopes": {
            item.name: item.registry["delivery_scope"]
            for item in items["foundation"]
        },
        "compiled_foundation_skills": compiled_foundation_skills,
        "domain_skills": [item.name for item in items["domain"]],
        "compiled_layer3_format": COMPILED_LAYER3_FORMAT,
        "compiled_layer3_references": compiled_by_skill,
        "foundation_mode": (
            "top-level"
            if profile == "dev"
            else "targeted-product-references"
        ),
        "domain_mode": (
            "targeted-references" if profile == "recommended" else "top-level"
        ),
        "agent_profiles": [profile_entry["name"] for profile_entry in profiles],
        "agent_profile_sha256": _agent_profile_digests(profiles, enforcement),
        "agent_profile_enforcement": enforcement["hosts"],
        "agent_profile_enforcement_source": {
            "path": HOST_ENFORCEMENT_SOURCE.relative_to(ROOT).as_posix(),
            "schema_version": enforcement["schema_version"],
            "sha256": hashlib.sha256(HOST_ENFORCEMENT_SOURCE.read_bytes()).hexdigest(),
            "summary": enforcement["source_summary"],
        },
        "core_model": {
            "path": CORE_CONTRACTS_PATH.relative_to(ROOT).as_posix(),
            "schema_version": CORE_CONTRACTS["schema_version"],
            "sha256": hashlib.sha256(CORE_CONTRACTS_PATH.read_bytes()).hexdigest(),
            "kind": CORE_CONTRACTS["kind"],
        },
    }
    (profile_root / BUILD_MANIFEST_NAME).write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _source_version() -> str:
    pyproject = ROOT / "pyproject.toml"
    if not pyproject.is_file():
        return "unknown"
    for line in pyproject.read_text(encoding="utf-8").splitlines():
        match = re.match(r'^version\s*=\s*"([^"]+)"', line.strip())
        if match:
            return match.group(1)
    return "unknown"


def _copy_skill_tree(source: Path, destination: Path) -> None:
    def ignore(_directory: str, names: list[str]) -> set[str]:
        return {
            name
            for name in names
            if name in {".DS_Store", "__pycache__"} or name.endswith((".pyc", ".pyo"))
        }

    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination, ignore=ignore)


def _reset_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def _clean_legacy_dist_artifacts() -> None:
    if not DIST_DIR.exists():
        return
    directory_names = {
        ".changeforge-packs",
        ".changeforge-control",
        "hooks",
        "runtime_governance",
    }
    file_names = {
        ".changeforge-hook-manifest.json",
        "changeforge-hooks.json",
        "settings.changeforge-hooks.fragment.json",
        "hooks.json",
        "changeforge-route-preflight.md",
        "changeforge-professional-contract.md",
    }
    for path in sorted(DIST_DIR.rglob("*"), key=lambda value: len(value.parts), reverse=True):
        if path.is_dir() and path.name in directory_names:
            shutil.rmtree(path)
            continue
        if not path.is_file():
            continue
        if path.name in file_names or path.name.startswith("changeforge_") and path.suffix == ".py":
            path.unlink()
    universal_bootstrap = DIST_DIR / "universal" / "bootstrap"
    if universal_bootstrap.exists():
        shutil.rmtree(universal_bootstrap)
    legacy_copilot_profiles = DIST_DIR / "copilot" / "project" / ".github" / "copilot" / "agents"
    if legacy_copilot_profiles.exists():
        shutil.rmtree(legacy_copilot_profiles)


def _cleanup_legacy_zip_layout() -> None:
    OPENAI_ZIP_DIR.mkdir(parents=True, exist_ok=True)
    for path in OPENAI_ZIP_DIR.iterdir():
        if path.is_file() and path.suffix == ".zip":
            path.unlink()
        elif path.is_dir() and path.name not in PROFILES:
            shutil.rmtree(path)


def _package_openai_zips(source_root: Path, zip_root: Path) -> int:
    skill_dirs = [
        path
        for path in sorted(source_root.iterdir())
        if path.is_dir() and not path.name.startswith(".")
    ]
    for skill_dir in skill_dirs:
        _validate_zip_source(skill_dir)
        _write_skill_zip(skill_dir, zip_root / f"{skill_dir.name}.zip")
    return len(skill_dirs)


def _validate_zip_source(skill_dir: Path) -> None:
    if not NAME_RE.fullmatch(skill_dir.name):
        raise BuildError(f"{_display_path(skill_dir)} must use a safe Skill name")
    symlinks = [path for path in sorted(skill_dir.rglob("*")) if path.is_symlink()]
    if symlinks:
        raise BuildError(f"{_display_path(symlinks[0])} must not be a symlink")
    files = [path for path in sorted(skill_dir.rglob("*")) if path.is_file()]
    root_skill = skill_dir / "SKILL.md"
    if not root_skill.is_file() or root_skill.is_symlink():
        raise BuildError(f"{_display_path(skill_dir)} is missing root SKILL.md")
    skill_files = [path for path in files if path.name == "SKILL.md"]
    if skill_files != [root_skill]:
        raise BuildError(f"{_display_path(skill_dir)} must contain exactly one SKILL.md")
    if len(files) > MAX_ZIP_FILES:
        raise BuildError(f"{_display_path(skill_dir)} exceeds zip file-count limit")
    total = 0
    for path in files:
        size = path.stat().st_size
        if size > MAX_ZIP_FILE_BYTES:
            raise BuildError(f"{_display_path(path)} exceeds zip file-size limit")
        total += size
    if total > MAX_ZIP_BYTES:
        raise BuildError(f"{_display_path(skill_dir)} exceeds zip size limit")


def _write_skill_zip(skill_dir: Path, zip_path: Path) -> None:
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(skill_dir.rglob("*")):
            if not path.is_file():
                continue
            relative = path.relative_to(skill_dir)
            info = zipfile.ZipInfo(f"{skill_dir.name}/{relative.as_posix()}", ZIP_TIMESTAMP)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, path.read_bytes())


def _string_list(value: object) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item).strip() for item in value if isinstance(item, str) and item.strip()]


if __name__ == "__main__":
    raise SystemExit(main())
