#!/usr/bin/env python3
"""Generate a ChangeForge scenario showcase from bounded Markdown examples."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

from validation_utils import load_yaml_file


ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class ShowcaseScenario:
    path: Path
    name: str
    prompt_summary: str
    route_path: str
    profiles: tuple[str, ...]
    professional_skills: tuple[str, ...]
    layer3_skills: tuple[str, ...]
    evidence_obligations: tuple[str, ...]


def _known_names(root: Path) -> tuple[set[str], set[str]]:
    professional = load_yaml_file(root / "src/registry/professional-skills.yaml")["professional_skills"]
    foundation = load_yaml_file(root / "src/registry/foundation-skills.yaml")["foundation_skills"]
    domain = load_yaml_file(root / "src/registry/domain-skills.yaml")["domain_skills"]
    return (
        {item["name"] for item in professional},
        {item["name"] for item in [*foundation, *domain]},
    )


def _scenario_name(path: Path) -> str:
    return path.name[3:].replace("-", " ").title()


def _first_prose(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            return stripped
    return "Not supplied."


def _path_summary(text: str) -> str:
    match = re.search(r"^## Path\s*$\n+(.*?)(?=^## |\Z)", text, re.M | re.S)
    if not match:
        return "Not supplied."
    return " ".join(line.strip() for line in match.group(1).splitlines() if line.strip())


def _evidence(path: Path) -> tuple[str, ...]:
    """Return top-level bullets with their indented continuation lines intact."""

    bullets: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("- "):
            bullets.append(line[2:].strip())
            continue
        if bullets and line[:1].isspace() and line.strip():
            bullets[-1] = f"{bullets[-1]} {line.strip()}"
    return tuple(bullets)


def collect_scenarios(root: Path) -> list[ShowcaseScenario]:
    professional, layer3 = _known_names(root)
    result: list[ShowcaseScenario] = []
    for directory in sorted((root / "examples").glob("[0-9][0-9]-*")):
        if not directory.is_dir():
            continue
        route = (directory / "expected-route.md").read_text(encoding="utf-8")
        backticks = set(re.findall(r"`([a-z0-9-]+)`", route))
        result.append(
            ShowcaseScenario(
                path=directory,
                name=_scenario_name(directory),
                prompt_summary=_first_prose(directory / "prompt.md"),
                route_path=_path_summary(route),
                profiles=tuple(sorted(backticks & {"analysis-agent", "task-agent", "review-agent"})),
                professional_skills=tuple(sorted(backticks & professional)),
                layer3_skills=tuple(sorted(backticks & layer3)),
                evidence_obligations=_evidence(directory / "expected-evidence.md"),
            )
        )
    return result


def _csv(values: tuple[str, ...]) -> str:
    return ", ".join(f"`{value}`" for value in values) if values else "`none`"


def render_showcase(root: Path) -> str:
    lines = [
        "# Scenario Showcase",
        "",
        "This generated view summarizes the bounded Direct, Analyzed, and Review contracts in `examples/`. It is deterministic documentation, not host-performance, real-host accuracy, or installed-experience evidence.",
        "",
        "_Generated by `python3 scripts/generate-examples-showcase.py --out docs/SHOWCASE.md`. Do not edit by hand._",
        "",
    ]
    for scenario in collect_scenarios(root):
        link = f"../{scenario.path.relative_to(root)}"
        lines.extend(
            [
                f"## {scenario.name}",
                "",
                f"- Example: [{scenario.path.name}]({link})",
                f"- Request: {scenario.prompt_summary}",
                f"- Path decision: {scenario.route_path}",
                f"- Profiles: {_csv(scenario.profiles)}",
                f"- Professional Skills: {_csv(scenario.professional_skills)}",
                f"- Triggered Layer 3 Skills: {_csv(scenario.layer3_skills)}",
                "- Evidence obligations:",
                *(
                    [f"  - {item}" for item in scenario.evidence_obligations]
                    or ["  - Not supplied."]
                ),
                "",
            ]
        )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    out = Path(args.out)
    rendered = render_showcase(ROOT)
    if args.check:
        if not out.is_file() or out.read_text(encoding="utf-8") != rendered:
            print(f"generate-examples-showcase: ERROR: {out} is stale", file=sys.stderr)
            return 1
        print("generate-examples-showcase: committed output is fresh")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(rendered, encoding="utf-8")
    print(f"wrote examples showcase to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
