#!/usr/bin/env python3
"""Generate a human-readable local marketplace catalog from source indexes."""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path
from typing import Any

from validation_utils import EXPECTED_PROFILE_TOP_LEVEL_COUNTS, load_yaml_file


ROOT = Path(__file__).resolve().parents[1]
PROFILES = ("recommended", "full", "dev")


def _load_exporter():
    spec = importlib.util.spec_from_file_location(
        "export_marketplace_index_for_catalog",
        ROOT / "scripts" / "export-marketplace-index.py",
    )
    if spec is None or spec.loader is None:
        raise RuntimeError("unable to load export-marketplace-index.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


EXPORTER = _load_exporter()


def _capability_groups(root: Path) -> dict[str, str]:
    registry = load_yaml_file(root / "src" / "registry" / "capabilities.yaml")
    return {
        str(item["name"]): str(item.get("group", "ungrouped"))
        for item in registry.get("capabilities", [])
    }


def _items_by_name(indexes: dict[str, dict[str, Any]], reference_profile: str) -> dict[str, dict[str, Any]]:
    return {
        str(item["name"]): item
        for item in indexes[reference_profile]["items"]
        if isinstance(item, dict)
    }


def _exposure(indexes: dict[str, dict[str, Any]], name: str) -> str:
    parts: list[str] = []
    for profile in PROFILES:
        item = next(
            item
            for item in indexes[profile]["items"]
            if isinstance(item, dict) and item.get("name") == name
        )
        visibility = item["profile_visibility"]
        if visibility["top_level"]:
            status = "top-level"
        elif visibility["compiled_reference"]:
            status = "compiled-reference"
        else:
            status = "router-index"
        parts.append(f"{profile}: {status}")
    return "; ".join(parts)


def _csv(values: list[Any]) -> str:
    strings = [str(value) for value in values if str(value).strip()]
    return ", ".join(f"`{value}`" for value in strings) if strings else "`none`"


def _line(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def generate_catalog(root: Path, reference_profile: str) -> dict[str, Any]:
    """Generate the catalog payload from the marketplace index exporter."""
    indexes = {profile: EXPORTER.export_index(root, profile) for profile in PROFILES}
    items = _items_by_name(indexes, reference_profile)
    capability_groups = _capability_groups(root)
    return {
        "reference_profile": reference_profile,
        "indexes": indexes,
        "items": items,
        "capability_groups": capability_groups,
    }


def _professional_items(payload: dict[str, Any]) -> list[dict[str, Any]]:
    return sorted(
        [item for item in payload["items"].values() if item["type"] == "professional_skill"],
        key=lambda item: item["name"],
    )


def _capability_items(payload: dict[str, Any]) -> list[dict[str, Any]]:
    return sorted(
        [item for item in payload["items"].values() if item["type"] == "foundation_capability"],
        key=lambda item: item["name"],
    )


def _domain_items(payload: dict[str, Any]) -> list[dict[str, Any]]:
    return sorted(
        [item for item in payload["items"].values() if item["type"] == "domain_extension"],
        key=lambda item: item["name"],
    )


def _browse_by(items: list[dict[str, Any]], field: str) -> dict[str, list[str]]:
    grouped: dict[str, list[str]] = {}
    for item in items:
        for value in item.get(field, []):
            grouped.setdefault(str(value), []).append(str(item["name"]))
    return {key: sorted(values) for key, values in sorted(grouped.items())}


def render_catalog(payload: dict[str, Any]) -> str:
    """Render the local marketplace catalog as Markdown."""
    indexes = payload["indexes"]
    all_items = list(payload["items"].values())
    capability_groups = payload["capability_groups"]
    lines = [
        "# Marketplace Catalog",
        "",
        "This generated catalog is a local discovery view over ChangeForge skills, foundation capabilities, and domain extensions. Official Codex and Claude marketplace publishing is intentionally not implemented, and this catalog must not be used to claim official marketplace availability.",
        "",
        "_Generated by `python3 scripts/generate-marketplace-catalog.py --profile recommended --out docs/MARKETPLACE_CATALOG.md`. Do not edit by hand._",
        "",
        "## Profile Summary",
        "",
        "| Profile | Top-Level Count | Exposure Rule |",
        "| --- | ---: | --- |",
        f"| `recommended` | {EXPECTED_PROFILE_TOP_LEVEL_COUNTS['recommended']} | 19 professional skills top-level; foundation capabilities compiled into references; domain extensions indexed for routing. |",
        f"| `full` | {EXPECTED_PROFILE_TOP_LEVEL_COUNTS['full']} | 19 professional skills plus 7 domain extensions top-level; foundation capabilities compiled into references. |",
        f"| `dev` | {EXPECTED_PROFILE_TOP_LEVEL_COUNTS['dev']} | 19 professional skills plus 117 foundation capabilities plus 7 domain extensions top-level. |",
        "",
        "## Professional Skills",
        "",
        "| Name | Summary | Triggers | Required Quality Gates |",
        "| --- | --- | --- | --- |",
    ]
    for item in _professional_items(payload):
        lines.append(
            f"| `{item['name']}` | {_line(item['summary'])} | {_csv(item['triggers'])} | {_csv(item['required_quality_gates'])} |"
        )

    lines.extend(["", "## Foundation Capabilities By Group", ""])
    grouped_capabilities: dict[str, list[dict[str, Any]]] = {}
    for item in _capability_items(payload):
        grouped_capabilities.setdefault(capability_groups.get(item["name"], "ungrouped"), []).append(item)
    for group, capabilities in sorted(grouped_capabilities.items()):
        lines.extend(
            [
                f"### {group}",
                "",
                "| Name | Used By | Triggers | Expected Outputs |",
                "| --- | --- | --- | --- |",
            ]
        )
        for item in capabilities:
            lines.append(
                f"| `{item['name']}` | {_csv(item['used_by'])} | {_csv(item['triggers'])} | {_csv(item['expected_outputs'])} |"
            )
        lines.append("")

    lines.extend(
        [
            "## Domain Extensions",
            "",
            "| Name | Summary | Profile Exposure |",
            "| --- | --- | --- |",
        ]
    )
    for item in _domain_items(payload):
        lines.append(f"| `{item['name']}` | {_line(item['summary'])} | {_exposure(indexes, item['name'])} |")

    lines.extend(["", "## Browse By Quality Gate", ""])
    for gate, names in _browse_by(all_items, "required_quality_gates").items():
        lines.append(f"- `{gate}`: {_csv(names)}")

    lines.extend(["", "## Browse By Risk Trigger", ""])
    for trigger, names in _browse_by(all_items, "triggers").items():
        lines.append(f"- `{trigger}`: {_csv(names)}")

    lines.extend(["", "## Browse By Profile Exposure", ""])
    for profile in PROFILES:
        top_level = [
            str(item["name"])
            for item in indexes[profile]["items"]
            if item["profile_visibility"]["top_level"]
        ]
        compiled = [
            str(item["name"])
            for item in indexes[profile]["items"]
            if item["profile_visibility"]["compiled_reference"]
        ]
        lines.append(f"- `{profile}` top-level: {_csv(sorted(top_level))}")
        lines.append(f"- `{profile}` compiled references: {_csv(sorted(compiled))}")
    lines.append("")
    return "\n".join(lines)


def _check_file(path: Path, expected: str) -> list[str]:
    if not path.exists():
        return [f"{path} does not exist"]
    if path.read_text(encoding="utf-8") != expected:
        return [f"{path} is stale"]
    return []


def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint for writing or checking the generated catalog."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", choices=PROFILES, default="recommended")
    parser.add_argument("--out", required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    rendered = render_catalog(generate_catalog(ROOT, args.profile))
    out = Path(args.out)
    if args.check:
        errors = _check_file(out, rendered)
        if errors:
            for error in errors:
                print(f"generate-marketplace-catalog: ERROR: {error}", file=sys.stderr)
            return 1
        print("generate-marketplace-catalog: committed output is fresh")
        return 0

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(rendered, encoding="utf-8")
    print(f"wrote marketplace catalog to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
