#!/usr/bin/env python3
"""Generate human-review candidate artifacts from a telemetry suggestion.

This tool turns one reviewed telemetry suggestion into a *candidate* golden
routing case, hook fixture, or agent-behavior sample. It never edits
``routing-rules.yaml``, ``SKILL.md``, ``capabilities.yaml``, or any other skill
rule. It only writes skeleton files under ``evals/routing``,
``tests/fixtures/hooks``, or ``evals/agent-behavior/samples`` for a human to
review, complete, and commit.

By default it is a dry run and prints the plan. Pass ``--write`` to write files.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from telemetry_utils import dump_yaml
from validation_utils import load_yaml_file, ValidationProblem


ROOT = Path(__file__).resolve().parents[1]
NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")

# The only directories this tool may write into. Skill rules are never targeted.
ALLOWED_TARGETS = {
    "evals/routing": ("yaml", "_routing_case"),
    "tests/fixtures/hooks": ("json", "_hook_fixture"),
    "evals/agent-behavior/samples": ("yaml", "_behavior_sample"),
}
FORBIDDEN_TARGET_HINTS = (
    "routing-rules",
    "skill.md",
    "capabilities.yaml",
    "src/registry",
    "src\\registry",
)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(sys.argv[1:] if argv is None else argv)
    repo_root = (args.repo_root or ROOT).expanduser()

    try:
        suggestions = _load_suggestions(args.suggestions)
    except ValidationProblem as exc:
        print(f"promote-telemetry-suggestion: ERROR: {exc}", file=sys.stderr)
        return 1

    suggestion = _find_suggestion(suggestions, args.id)
    if suggestion is None:
        print(
            f"promote-telemetry-suggestion: ERROR: suggestion id '{args.id}' not found in "
            f"{args.suggestions}",
            file=sys.stderr,
        )
        return 1

    target = str(suggestion.get("promotion_target") or "").strip()
    if target not in ALLOWED_TARGETS:
        print(
            f"promote-telemetry-suggestion: ERROR: unsupported promotion_target '{target}'. "
            f"Allowed: {', '.join(sorted(ALLOWED_TARGETS))}",
            file=sys.stderr,
        )
        return 1
    if _looks_forbidden(target):
        print(
            "promote-telemetry-suggestion: ERROR: refusing to target a skill rule file.",
            file=sys.stderr,
        )
        return 1

    extension, renderer = ALLOWED_TARGETS[target]
    case_name = _case_name(suggestion, args.id)
    rel_path = f"{target}/{case_name}.{extension}"
    out_path = repo_root / target / f"{case_name}.{extension}"
    content = globals()[renderer](case_name, suggestion)

    if out_path.exists() and not args.force:
        print(
            f"promote-telemetry-suggestion: ERROR: {rel_path} already exists; "
            "use --force to overwrite (and review carefully).",
            file=sys.stderr,
        )
        return 1

    if not args.write:
        print(f"promote-telemetry-suggestion: DRY RUN for suggestion '{args.id}'")
        print(f"- promotion target: {target}")
        print(f"- would write: {rel_path}")
        print("- requires human review before committing")
        print("--- preview ---")
        print(content)
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"promote-telemetry-suggestion: wrote candidate {rel_path}")
    print("promote-telemetry-suggestion: review and complete the file before committing.")
    _record_promotion(args, suggestion, rel_path)
    return 0


def _load_suggestions(path: Path) -> list[dict[str, Any]]:
    data = load_yaml_file(path)
    if not isinstance(data, dict):
        raise ValidationProblem(f"{path}: suggestions file must be a mapping")
    suggestions = data.get("suggestions")
    if not isinstance(suggestions, list):
        raise ValidationProblem(f"{path}: missing 'suggestions' list")
    return [item for item in suggestions if isinstance(item, dict)]


def _find_suggestion(suggestions: list[dict[str, Any]], suggestion_id: str) -> dict[str, Any] | None:
    for suggestion in suggestions:
        if str(suggestion.get("id")) == suggestion_id:
            return suggestion
    return None


def _case_name(suggestion: dict[str, Any], suggestion_id: str) -> str:
    raw = str(suggestion.get("id") or suggestion_id)
    slug = re.sub(r"[^a-z0-9]+", "-", raw.casefold()).strip("-")
    candidate = f"telemetry-{slug}" if slug else "telemetry-candidate"
    return candidate if NAME_RE.fullmatch(candidate) else "telemetry-candidate"


def _header_comment(suggestion: dict[str, Any]) -> str:
    return (
        "# Generated by scripts/promote-telemetry-suggestion.py from a telemetry suggestion.\n"
        "# Candidate only: review, complete the TODOs, and validate before committing.\n"
    )


def _routing_case(case_name: str, suggestion: dict[str, Any]) -> str:
    data = {
        "generated_from_telemetry": True,
        "requires_human_review": True,
        "source_suggestion_id": str(suggestion.get("id", "")),
        "id": case_name,
        "description": _one_line(suggestion.get("evidence")),
        "prompt": "TODO: replace with a concrete, reproducible prompt for this route.",
        "expected": {
            "complexity": "L1",
            "risk_level": "low",
            "risk_triggers": [],
            "skills": [],
            "capabilities": [],
            "domain_extensions": [],
            "quality_gates": [],
        },
        "forbidden": {
            "skills": [],
            "capabilities": [],
            "domain_extensions": [],
            "quality_gates": [],
        },
        "notes": _notes(suggestion),
    }
    return _header_comment(suggestion) + dump_yaml(data)


def _behavior_sample(case_name: str, suggestion: dict[str, Any]) -> str:
    data = {
        "generated_from_telemetry": True,
        "requires_human_review": True,
        "source_suggestion_id": str(suggestion.get("id", "")),
        "id": case_name,
        "description": _one_line(suggestion.get("evidence")),
        "prompt": "TODO: replace with the real prompt the agent handled.",
        "validation_evidence": False,
        "residual_risk": False,
        "expected": {
            "selected_skills": [],
            "forbidden_skills": [],
            "selected_capabilities": [],
            "required_references": [],
            "required_quality_gates": [],
        },
        "manifest": {
            "schema_version": 1,
            "selected_skills": [],
            "selected_capabilities": [],
            "selected_domain_extensions": [],
            "required_references": [],
            "required_quality_gates": [],
            "skipped_quality_gates": [],
        },
        "notes": _notes(suggestion),
    }
    return _header_comment(suggestion) + dump_yaml(data)


def _hook_fixture(case_name: str, suggestion: dict[str, Any]) -> str:
    data = {
        "_generated_from_telemetry": True,
        "_requires_human_review": True,
        "_source_suggestion_id": str(suggestion.get("id", "")),
        "_note": "Synthetic hook event fixture. Replace tool/paths with a concrete reproduction.",
        "_suggested_action": _one_line(suggestion.get("suggested_action")),
        "hook_event_name": "PostToolUse",
        "runtime": "codex",
        "tool_name": "apply_patch",
        "tool_input": {"file_path": "TODO/replace/with/real/path"},
    }
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def _notes(suggestion: dict[str, Any]) -> str:
    return (
        f"Derived from telemetry suggestion {suggestion.get('id', '')} "
        f"({suggestion.get('type', '')}). {_one_line(suggestion.get('suggested_action'))}"
    )


def _one_line(value: Any) -> str:
    return " ".join(str(value or "").split())


def _looks_forbidden(target: str) -> bool:
    lowered = target.casefold()
    return any(hint in lowered for hint in FORBIDDEN_TARGET_HINTS)


def _record_promotion(args: argparse.Namespace, suggestion: dict[str, Any], rel_path: str) -> None:
    if not args.telemetry_root or not args.repo_hash:
        return
    try:
        promoted_dir = args.telemetry_root.expanduser() / args.repo_hash / "promoted"
        promoted_dir.mkdir(parents=True, exist_ok=True)
        record = {
            "promoted_at": datetime.now(timezone.utc).isoformat(),
            "source_suggestion_id": str(suggestion.get("id", "")),
            "type": str(suggestion.get("type", "")),
            "candidate_path": rel_path,
        }
        date_stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        target = promoted_dir / f"{date_stamp}-promoted.jsonl"
        with target.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(record, sort_keys=True) + "\n")
    except OSError:
        return


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a human-review candidate from a telemetry suggestion."
    )
    parser.add_argument("--id", required=True, help="Suggestion id to promote.")
    parser.add_argument(
        "--suggestions",
        required=True,
        type=Path,
        help="Path to a suggestions YAML produced by review-agent-telemetry.py.",
    )
    parser.add_argument("--write", action="store_true", help="Write files (default is dry run).")
    parser.add_argument("--force", action="store_true", help="Overwrite an existing candidate file.")
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="Repository root for generated candidate paths (defaults to this repo).",
    )
    parser.add_argument("--telemetry-root", type=Path, default=None)
    parser.add_argument("--repo-hash", default=None)
    return parser.parse_args(argv)


if __name__ == "__main__":
    raise SystemExit(main())
