#!/usr/bin/env python3
"""Validate global source invariants across ChangeForge authoring assets."""

from __future__ import annotations

import importlib.util
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Any

from validation_utils import (
    ValidationProblem,
    fail_many,
    has_section,
    load_yaml_file,
    parse_frontmatter,
    registry_items,
    relpath,
)


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
REGISTRY_DIR = SRC / "registry"
SKILLS_REGISTRY = REGISTRY_DIR / "skills.yaml"
CAPABILITIES_REGISTRY = REGISTRY_DIR / "capabilities.yaml"
DOMAIN_EXTENSIONS_REGISTRY = REGISTRY_DIR / "domain-extensions.yaml"
PROFESSIONAL_SKILLS_DIR = SRC / "professional-skills"
CAPABILITIES_DIR = SRC / "foundation" / "capabilities"
DOMAIN_EXTENSIONS_DIR = SRC / "domain-extensions"
HOOKS_DOC = ROOT / "docs" / "HOOKS.md"
DIST_DIR = ROOT / "dist"

GENERATED_MARKER = "<!-- Generated by scripts/build.py; do not edit by hand. -->"
PROFILE_NAMES = ("recommended", "full", "dev")
RUNTIME_REFERENCE_PROFILES = ("recommended", "full")

PROFESSIONAL_REQUIRED_SECTIONS = (
    "Mission",
    "When To Use",
    "Do Not Use When",
    "Non-Negotiable Rules",
    "Output Contract",
    "Evidence Contract",
    "Quality Gate",
    "Handoff",
    "Completion Criteria",
)

DOMAIN_REQUIRED_SECTIONS = (
    "Do Not Use When",
    "Quality Gate",
    "Handoff",
    "Completion Criteria",
)

ROUTE_LEVEL_OWNER_HINTS = {
    "change-forge-router",
    "agent-execution-discipline",
    "agent-workflow-state-machine",
    "agent-tool-permission-sandbox",
    "execution-trajectory-analysis",
    "project-memory-governance",
    "validation-broker",
    "executor-adapter-protocol",
    "quality-test-gate",
    "security-privacy-gate",
    "ai-code-review-refactor",
    "change-documentation-gate",
    "delivery-release-gate",
}

LEGACY_USED_BY_ALIASES: dict[str, str] = {}

REQUIRED_BROKER_PATH_PATTERNS = (
    "src/registry/**",
    "src/professional-skills/**",
    "src/foundation/capabilities/**",
    "src/domain-extensions/**",
    "src/hook-runtime/**",
    "src/runtime_governance/**",
    "src/project_memory/**",
    "src/repository_intelligence/**",
    "src/validation_broker/**",
    "src/trajectory/**",
)

AUTHORING_PATH_TOKENS = (
    "src/registry",
    "src/professional-skills",
    "src/foundation/capabilities",
    "src/domain-extensions",
    "src/hook-runtime",
    "src/runtime_governance",
    "src/project_memory",
    "src/repository_intelligence",
    "src/validation_broker",
    "src/trajectory",
)

PROJECT_MEMORY_REQUIRED_MARKERS = (
    "src/project_memory/schemas/memory-event.v1.schema.json",
    "src/project_memory/privacy.py",
    "src/project_memory/store/retention.py",
    "src/project_memory/store/projection.py",
    "src/project_memory/retrieval/deterministic_ranker.py",
)

REPOSITORY_INTELLIGENCE_REQUIRED_MARKERS = (
    "src/repository_intelligence/graph/repo_indexer.py",
    "src/repository_intelligence/cache/repo_hash.py",
    "src/repository_intelligence/packaging/context_pack_builder.py",
)


@dataclass
class ValidationResult:
    """Validation output separated into blocking errors and advisory warnings."""

    errors: list[str]
    warnings: list[str]


def validate_repository(root: Path = ROOT) -> ValidationResult:
    """Return all source invariant errors and warnings for *root*."""
    errors: list[str] = []
    warnings: list[str] = []
    _set_root(root)
    _validate_skill_registry(errors)
    capability_entries = _validate_capability_registry(errors, warnings)
    _validate_capability_references(capability_entries, errors, warnings)
    _validate_domain_extensions(errors)
    _validate_source_runtime_boundary(errors, warnings)
    _validate_hook_runtime_consistency(errors, warnings)
    _validate_validation_broker_mapping(errors)
    _validate_memory_and_graph_coverage(errors)
    return ValidationResult(errors=errors, warnings=warnings)


def _set_root(root: Path) -> None:
    global ROOT, SRC, REGISTRY_DIR, SKILLS_REGISTRY, CAPABILITIES_REGISTRY
    global DOMAIN_EXTENSIONS_REGISTRY, PROFESSIONAL_SKILLS_DIR, CAPABILITIES_DIR
    global DOMAIN_EXTENSIONS_DIR, HOOKS_DOC, DIST_DIR
    ROOT = root
    SRC = ROOT / "src"
    REGISTRY_DIR = SRC / "registry"
    SKILLS_REGISTRY = REGISTRY_DIR / "skills.yaml"
    CAPABILITIES_REGISTRY = REGISTRY_DIR / "capabilities.yaml"
    DOMAIN_EXTENSIONS_REGISTRY = REGISTRY_DIR / "domain-extensions.yaml"
    PROFESSIONAL_SKILLS_DIR = SRC / "professional-skills"
    CAPABILITIES_DIR = SRC / "foundation" / "capabilities"
    DOMAIN_EXTENSIONS_DIR = SRC / "domain-extensions"
    HOOKS_DOC = ROOT / "docs" / "HOOKS.md"
    DIST_DIR = ROOT / "dist"


def _validate_skill_registry(errors: list[str]) -> list[dict[str, Any]]:
    context = "src/registry/skills.yaml"
    data = _load_registry(SKILLS_REGISTRY, "changeforge.skills", context, errors)
    entries = registry_items(data, "skills", SKILLS_REGISTRY, errors)
    if not entries:
        errors.append(f"{context}: skills must be non-empty")
        return []

    seen_names: dict[str, int] = {}
    seen_paths: dict[str, int] = {}
    valid_entries: list[dict[str, Any]] = []
    for index, entry in enumerate(entries):
        item_context = f"{context}:skills[{index}]"
        if not isinstance(entry, dict):
            errors.append(f"{item_context}: entry must be a mapping")
            continue
        valid_entries.append(entry)
        name = _required_text(entry, "name", item_context, errors)
        path_value = _required_text(entry, "path", item_context, errors)
        if name:
            _check_unique(seen_names, name, item_context, "name", errors)
        if path_value:
            _check_unique(seen_paths, path_value, item_context, "path", errors)
            if _runtime_or_generated_path(path_value):
                errors.append(
                    f"{item_context}: path must point to source professional skill content, "
                    f"not runtime/generated content: {path_value}"
                )
            skill_dir = ROOT / path_value
            skill_file = skill_dir / "SKILL.md"
            if not skill_dir.exists():
                errors.append(
                    f"{item_context}: missing path {path_value}; create the directory or fix the registry path"
                )
                continue
            if not skill_file.is_file():
                errors.append(f"{item_context}: missing SKILL.md at {path_value}/SKILL.md")
                continue
            _validate_professional_skill_file(skill_file, name, errors)
    return valid_entries


def _validate_professional_skill_file(skill_file: Path, registry_name: str | None, errors: list[str]) -> None:
    file_context = _display(skill_file)
    try:
        metadata, _raw, body = parse_frontmatter(skill_file)
    except ValidationProblem as exc:
        errors.append(_clean_validation_error(exc))
        return
    if registry_name and metadata.get("name") != registry_name:
        errors.append(
            f"{file_context}: frontmatter name {metadata.get('name')!r} must match registry name {registry_name!r}"
        )
    if metadata.get("changeforge_kind") != "professional-skill":
        errors.append(f"{file_context}: changeforge_kind must be professional-skill")
    for key in ("license", "changeforge_version"):
        if not metadata.get(key):
            errors.append(f"{file_context}: missing required frontmatter {key!r}")
    for section in PROFESSIONAL_REQUIRED_SECTIONS:
        if not has_section(body, section):
            errors.append(f"{file_context}: missing required section '{section}'")


def _validate_capability_registry(errors: list[str], warnings: list[str]) -> list[dict[str, Any]]:
    context = "src/registry/capabilities.yaml"
    data = _load_registry(CAPABILITIES_REGISTRY, "changeforge.capabilities", context, errors)
    entries = registry_items(data, "capabilities", CAPABILITIES_REGISTRY, errors)
    if not entries:
        errors.append(f"{context}: capabilities must be non-empty")
        return []

    skill_names = _registry_names(SKILLS_REGISTRY, "skills")
    domain_extension_names = _registry_names(DOMAIN_EXTENSIONS_REGISTRY, "domain_extensions")
    seen_ids: dict[str, int] = {}
    seen_names: dict[str, int] = {}
    seen_paths: dict[str, int] = {}
    valid_entries: list[dict[str, Any]] = []

    for index, entry in enumerate(entries):
        item_context = f"{context}:capabilities[{index}]"
        if not isinstance(entry, dict):
            errors.append(f"{item_context}: entry must be a mapping")
            continue
        valid_entries.append(entry)
        capability_id = entry.get("id")
        if not isinstance(capability_id, str) or not capability_id.strip():
            errors.append(f"{item_context}: id must be a non-empty string")
        else:
            _check_unique(seen_ids, capability_id, item_context, "id", errors)
        name = _required_text(entry, "name", item_context, errors)
        path_value = _required_text(entry, "path", item_context, errors)
        if name:
            _check_unique(seen_names, name, item_context, "name", errors)
        if path_value:
            _check_unique(seen_paths, path_value, item_context, "path", errors)
            capability_dir = ROOT / path_value
            skill_file = capability_dir / "SKILL.md"
            if not capability_dir.exists():
                errors.append(
                    f"{item_context}: missing path {path_value}; create the capability directory or fix the path"
                )
            if entry.get("status") == "implemented" and not skill_file.is_file():
                errors.append(f"{item_context}: status implemented requires {path_value}/SKILL.md")
        for field in ("group", "triggers", "risk_notes", "expected_outputs"):
            if not _nonempty_field(entry.get(field)):
                errors.append(f"{item_context}: field {field!r} must be non-empty")
        used_by = entry.get("used_by")
        if not _nonempty_string_list(used_by):
            errors.append(f"{item_context}: field 'used_by' must be a non-empty list of strings")
            continue
        _validate_used_by(entry, index, entries, skill_names, domain_extension_names, errors, warnings)
    return valid_entries


def _validate_used_by(
    entry: dict[str, Any],
    index: int,
    entries: list[object],
    skill_names: set[str],
    domain_extension_names: set[str],
    errors: list[str],
    warnings: list[str],
) -> None:
    context = f"src/registry/capabilities.yaml:capabilities[{index}]"
    capability_names = {
        item.get("name")
        for item in entries
        if isinstance(item, dict) and isinstance(item.get("name"), str)
    }
    capability_by_name = {
        item["name"]: item
        for item in entries
        if isinstance(item, dict) and isinstance(item.get("name"), str)
    }
    unknown: list[str] = []
    used_by = [str(item).strip() for item in entry.get("used_by", [])]
    for target in used_by:
        if (
            target not in skill_names
            and target not in domain_extension_names
            and target not in capability_names
            and target not in LEGACY_USED_BY_ALIASES
        ):
            unknown.append(target)
    if unknown:
        errors.append(
            f"{context}: used_by references unknown item(s): {', '.join(sorted(unknown))}; "
            "use a professional skill, domain extension, capability name, or explicit legacy alias"
        )
        return

    name = str(entry.get("name", ""))
    if bool(entry.get("route_level_capability")):
        if not set(used_by).intersection(ROUTE_LEVEL_OWNER_HINTS):
            errors.append(
                f"{context}: route_level_capability true must be used by change-forge-router "
                "or another route/runtime/agent governance owner"
            )
        if "route_level_capability" not in entry:
            errors.append(f"{context}: route-level capability must be explicit in registry")
        return

    if not _capability_traces_to_professional(name, capability_by_name, skill_names, set()):
        warnings.append(
            f"{context}: capability '{name}' has no direct or indirect professional skill owner; "
            "add a professional owner or document an indirect ownership reason"
        )


def _capability_traces_to_professional(
    capability_name: str,
    capability_by_name: dict[str, dict[str, Any]],
    skill_names: set[str],
    seen: set[str],
) -> bool:
    if capability_name in seen:
        return False
    seen.add(capability_name)
    entry = capability_by_name.get(capability_name)
    if not isinstance(entry, dict):
        return False
    used_by = [str(item).strip() for item in entry.get("used_by", []) if str(item).strip()]
    if any(item in skill_names for item in used_by):
        return True
    for item in used_by:
        alias_target = LEGACY_USED_BY_ALIASES.get(item)
        if alias_target in skill_names:
            return True
        if item in capability_by_name and _capability_traces_to_professional(
            item, capability_by_name, skill_names, seen
        ):
            return True
    return False


def _validate_capability_references(
    capability_entries: list[dict[str, Any]],
    errors: list[str],
    warnings: list[str],
) -> None:
    capability_files: dict[str, dict[str, Any]] = {}
    by_skill: dict[str, set[str]] = {}
    for entry in capability_entries:
        capability_id = entry.get("id")
        name = entry.get("name")
        if not isinstance(capability_id, str) or not isinstance(name, str):
            continue
        file_name = f"{capability_id}-{name}.md"
        if file_name in capability_files:
            errors.append(
                f"src/registry/capabilities.yaml: generated reference filename collision: {file_name}"
            )
        capability_files[file_name] = entry
        for used_by in entry.get("used_by", []) or []:
            if isinstance(used_by, str):
                by_skill.setdefault(used_by, set()).add(file_name)

    for references_dir, profile in _capability_reference_dirs():
        direct_files = sorted(path for path in references_dir.glob("*.md") if path.name != "index.md")
        for path in direct_files:
            entry = capability_files.get(path.name)
            if entry is None:
                errors.append(
                    f"{_display(path)}: generated capability reference does not map to a registry capability"
                )
                continue
            text = path.read_text(encoding="utf-8")
            if GENERATED_MARKER not in text:
                errors.append(
                    f"{_display(path)}: compiled capability reference must contain generated marker "
                    "or be regenerated from source"
                )
        skill_name = references_dir.parent.parent.name
        expected = by_skill.get(skill_name, set())
        if profile in RUNTIME_REFERENCE_PROFILES:
            found = {path.name for path in direct_files}
            missing = sorted(expected - found)
            if missing:
                errors.append(
                    f"{_display(references_dir)}: missing compiled capability reference(s) "
                    f"for profile {profile}: {', '.join(missing)}"
                )
        elif expected and not direct_files:
            warnings.append(
                f"{_display(references_dir)}: source/dev reference directory has no compiled "
                "capability files; recommended/full generated profiles are authoritative"
            )


def _capability_reference_dirs() -> list[tuple[Path, str]]:
    result: list[tuple[Path, str]] = []
    for skill_dir in _visible_dirs(PROFESSIONAL_SKILLS_DIR):
        refs = skill_dir / "references" / "capabilities"
        if refs.is_dir():
            result.append((refs, "source"))
    if DIST_DIR.is_dir():
        for profile_root in sorted(DIST_DIR.rglob("*")):
            if not profile_root.is_dir() or profile_root.name not in PROFILE_NAMES:
                continue
            profile = profile_root.name
            for skill_dir in _visible_dirs(profile_root):
                refs = skill_dir / "references" / "capabilities"
                if refs.is_dir():
                    result.append((refs, profile))
    return result


def _validate_domain_extensions(errors: list[str]) -> None:
    if not DOMAIN_EXTENSIONS_DIR.is_dir():
        errors.append("src/domain-extensions: missing domain extension directory")
        return
    extension_dirs = _visible_dirs(DOMAIN_EXTENSIONS_DIR)
    router_text = _read_text(PROFESSIONAL_SKILLS_DIR / "change-forge-router" / "SKILL.md")
    for extension_dir in extension_dirs:
        skill_file = extension_dir / "SKILL.md"
        if not skill_file.is_file():
            errors.append(f"{_display(extension_dir)}: domain extension directory must contain SKILL.md")
            continue
        try:
            metadata, _raw, body = parse_frontmatter(skill_file)
        except ValidationProblem as exc:
            errors.append(_clean_validation_error(exc))
            continue
        if metadata.get("changeforge_kind") != "domain-extension":
            errors.append(f"{_display(skill_file)}: changeforge_kind must be domain-extension")
        name = metadata.get("name")
        if name != extension_dir.name:
            errors.append(
                f"{_display(skill_file)}: frontmatter name {name!r} must match directory {extension_dir.name!r}"
            )
        if extension_dir.name not in router_text:
            errors.append(
                f"{_display(skill_file)}: router does not list domain extension '{extension_dir.name}'"
            )
        if not (has_section(body, "When To Use") or has_section(body, "Trigger Signals")):
            errors.append(
                f"{_display(skill_file)}: domain extension must include When To Use or current Trigger Signals section"
            )
        for section in DOMAIN_REQUIRED_SECTIONS:
            if not has_section(body, section):
                errors.append(f"{_display(skill_file)}: missing required section '{section}'")
    if "domain signal" not in router_text.casefold():
        errors.append(
            "src/professional-skills/change-forge-router/SKILL.md: router must state "
            "domain extensions are triggered by domain signals, not default-loaded"
        )


def _validate_source_runtime_boundary(errors: list[str], warnings: list[str]) -> None:
    pyproject = _read_text(ROOT / "pyproject.toml")
    if "install_src_directly = false" not in pyproject:
        errors.append("pyproject.toml: [tool.changeforge] must set install_src_directly = false")
    _validate_installer_sources(errors)
    _validate_dist_guardrails(errors)
    _validate_hook_templates_do_not_load_all_source_capabilities(errors)
    if not DIST_DIR.is_dir():
        warnings.append("dist: runtime output not present; source/dist runtime boundary checks are partial")


def _validate_installer_sources(errors: list[str]) -> None:
    install_module = _import_module(
        ROOT / "installers" / "changeforge_install.py",
        "changeforge_install_src_invariant",
        extra_paths=[ROOT / "installers"],
    )
    if install_module is None:
        errors.append("installers/changeforge_install.py: cannot import installer source map")
        return
    roots = []
    for attr in ("SOURCE_SKILL_ROOTS", "HOOK_SOURCE_ROOTS"):
        mapping = getattr(install_module, attr, None)
        if isinstance(mapping, dict):
            roots.extend(path for path in mapping.values() if isinstance(path, Path))
    for path in roots:
        try:
            relative = path.resolve().relative_to(ROOT.resolve())
        except ValueError:
            continue
        parts = relative.parts
        if parts and parts[0] == "src":
            errors.append(
                f"installers/changeforge_install.py: installer source root must not point to src/: {relative}"
            )
        if parts and parts[0] == "dist":
            continue


def _validate_dist_guardrails(errors: list[str]) -> None:
    if not DIST_DIR.is_dir():
        return
    for path in sorted(DIST_DIR.rglob("*")):
        relative = _display(path)
        parts = [part.casefold() for part in path.relative_to(DIST_DIR).parts]
        if "src" in parts:
            errors.append(f"{relative}: raw src directory installed in runtime output")
        if "registry" in parts:
            errors.append(f"{relative}: raw registry directory installed in runtime output")
        if path.is_file() and path.suffix not in {".zip", ".pyc"}:
            try:
                text = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue
            for token in AUTHORING_PATH_TOKENS:
                if (token in text or token.replace("/", "\\") in text) and not _hook_safe_source_reference(path):
                    errors.append(
                        f"{relative}: runtime content must not reference {token} authoring paths"
                    )
                    break


def _hook_safe_source_reference(path: Path) -> bool:
    normalized = _display(path).replace("\\", "/")
    hook_artifact_roots = (
        "/.codex/hooks/",
        "/.claude/hooks/",
        "/.github/hooks/changeforge/",
        "/.copilot/hooks/changeforge/",
    )
    return (
        any(marker in normalized for marker in hook_artifact_roots)
        or "/hooks/changeforge_runtime_route_resolver.py" in normalized
        or "/hooks/changeforge_skill_index.py" in normalized
        or "/hooks/repository_intelligence/graph/file_classifier.py" in normalized
        or "/hooks/changeforge/repository_intelligence/graph/file_classifier.py" in normalized
        or normalized.endswith(".changeforge-hook-manifest.json")
    )


def _validate_hook_templates_do_not_load_all_source_capabilities(errors: list[str]) -> None:
    templates_root = SRC / "hook-runtime" / "templates"
    if not templates_root.is_dir():
        errors.append("src/hook-runtime/templates: missing hook templates")
        return
    forbidden = (
        "src/foundation/capabilities",
        "load every capability",
        "read every capability",
        "load all capabilities",
        "read all capabilities",
    )
    for path in sorted(templates_root.rglob("*")):
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8").casefold()
        for token in forbidden:
            if token in text:
                errors.append(
                    f"{_display(path)}: hook template must not default-load source capabilities ({token})"
                )


def _validate_hook_runtime_consistency(errors: list[str], warnings: list[str]) -> None:
    if not HOOKS_DOC.is_file():
        errors.append("docs/HOOKS.md: missing hook runtime documentation")
        return
    runtime_module = _import_module(
        SRC / "runtime_governance" / "adapters" / "base.py",
        "runtime_adapter_base_src_invariant",
        extra_paths=[SRC],
        package_name="runtime_governance.adapters.base",
    )
    events_module = _import_module(
        SRC / "runtime_governance" / "events.py",
        "runtime_events_src_invariant",
        extra_paths=[SRC],
        package_name="runtime_governance.events",
    )
    gates_module = _import_module(
        SRC / "runtime_governance" / "gates.py",
        "runtime_gates_src_invariant",
        extra_paths=[SRC],
        package_name="runtime_governance.gates",
    )
    if runtime_module is not None:
        _compare_docs_adapter_matrix(HOOKS_DOC, runtime_module, errors, warnings)
    if runtime_module is not None and events_module is not None:
        event_values = {item.value for item in events_module.EventKind}
        for canonical, event_kind in getattr(runtime_module, "EVENT_KIND_BY_CANONICAL", {}).items():
            if event_kind not in event_values:
                errors.append(
                    "src/runtime_governance/adapters/base.py: "
                    f"canonical event {canonical} maps to unknown EventKind {event_kind}"
                )
    if gates_module is not None:
        outcomes = {item.value for item in gates_module.GateOutcome}
        required = {"pass", "warn", "block", "fail_open", "degraded"}
        missing = sorted(required - outcomes)
        if missing:
            errors.append(
                "src/runtime_governance/gates.py: GateOutcome missing docs/runtime semantics "
                f"{', '.join(missing)}"
            )


def _compare_docs_adapter_matrix(
    docs_path: Path,
    adapters_module: ModuleType,
    errors: list[str],
    warnings: list[str],
) -> None:
    rows = _parse_hook_matrix(docs_path.read_text(encoding="utf-8"))
    if not rows:
        errors.append("docs/HOOKS.md: adapter capability matrix table not found")
        return
    for label, runtime in _matrix_runtime_map().items():
        row = rows.get(label)
        if row is None:
            errors.append(f"docs/HOOKS.md: adapter capability matrix missing row '{label}'")
            continue
        try:
            adapter = adapters_module.adapter_capabilities_for(runtime)
        except Exception as exc:
            errors.append(f"adapter capabilities import failed for {runtime}: {exc}")
            continue
        documented_supported = set(_backtick_values(row[1]))
        actual_supported = set(adapter.supported_events)
        if "none" in row[1].casefold():
            documented_supported = set()
        if documented_supported != actual_supported:
            errors.append(
                f"docs/HOOKS.md: {label} supported events differ from adapter capabilities; "
                f"docs={sorted(documented_supported)} code={sorted(actual_supported)}"
            )
        documented_advisory = row[3].strip().casefold()
        actual_advisory = bool(adapter.advisory_context_supported)
        if documented_advisory in {"yes", "no"} and (documented_advisory == "yes") != actual_advisory:
            errors.append(f"docs/HOOKS.md: {label} advisory context differs from adapter capabilities")
        if documented_advisory not in {"yes", "no"}:
            warnings.append(f"docs/HOOKS.md: {label} advisory context is descriptive; exact check skipped")


def _parse_hook_matrix(text: str) -> dict[str, list[str]]:
    rows: dict[str, list[str]] = {}
    in_table = False
    for raw in text.splitlines():
        if raw.startswith("| Runtime | Supported events |"):
            in_table = True
            continue
        if not in_table:
            continue
        if raw.startswith("| ---"):
            continue
        if not raw.startswith("|"):
            if rows:
                break
            continue
        cells = [cell.strip() for cell in raw.strip().strip("|").split("|")]
        if len(cells) >= 6:
            rows[cells[0]] = cells
    return rows


def _matrix_runtime_map() -> dict[str, str]:
    return {
        "Codex": "codex",
        "Claude": "claude",
        "Copilot": "copilot",
        "Generic fallback": "generic",
        "Cline staged target": "cline",
        "Roo staged target": "roo",
        "OpenHands backend target": "openhands",
        "Gemini CLI placeholder": "gemini-cli",
        "Goose placeholder": "goose",
    }


def _validate_validation_broker_mapping(errors: list[str]) -> None:
    module = _import_module(
        SRC / "validation_broker" / "command_registry.py",
        "validation_broker_command_registry_src_invariant",
        extra_paths=[SRC],
        package_name="validation_broker.command_registry",
    )
    if module is None:
        errors.append("src/validation_broker/command_registry.py: cannot import command registry")
        return
    patterns = {
        pattern
        for entry in getattr(module, "REGISTRY", {}).values()
        if isinstance(entry, dict)
        for pattern in entry.get("path_patterns", ())
        if isinstance(pattern, str)
    }
    for required in REQUIRED_BROKER_PATH_PATTERNS:
        if required not in patterns:
            errors.append(
                "src/validation_broker/command_registry.py: missing known rd-skills "
                f"path mapping for {required}"
            )


def _validate_memory_and_graph_coverage(errors: list[str]) -> None:
    for marker in PROJECT_MEMORY_REQUIRED_MARKERS:
        if not (ROOT / marker).exists():
            errors.append(f"{marker}: required project memory source/schema is missing")
    if not (ROOT / "scripts" / "validate-project-memory.py").is_file():
        errors.append("scripts/validate-project-memory.py: project memory validator is required")
    if not (ROOT / "tests" / "project_memory").is_dir():
        errors.append("tests/project_memory: project memory tests are required")

    for marker in REPOSITORY_INTELLIGENCE_REQUIRED_MARKERS:
        if not (ROOT / marker).exists():
            errors.append(f"{marker}: required repository intelligence source is missing")
    for required in ("scripts/validate-repository-graph.py", "scripts/validate-context-pack.py"):
        if not (ROOT / required).is_file():
            errors.append(f"{required}: repository intelligence validator is required")
    if not (ROOT / "tests" / "repository_intelligence").is_dir():
        errors.append("tests/repository_intelligence: repository intelligence tests are required")


def _load_registry(path: Path, expected_kind: str, context: str, errors: list[str]) -> Any:
    if not path.is_file():
        errors.append(f"{context}: registry file is missing")
        return {}
    try:
        data = load_yaml_file(path)
    except ValidationProblem as exc:
        errors.append(_clean_validation_error(exc))
        return {}
    if not isinstance(data, dict):
        errors.append(f"{context}: registry must be a mapping")
        return {}
    if data.get("schema_version") is None:
        errors.append(f"{context}: schema_version is required")
    if data.get("kind") is None:
        errors.append(f"{context}: kind is required")
    elif data.get("kind") != expected_kind:
        errors.append(f"{context}: kind must be {expected_kind}")
    return data


def _registry_names(path: Path, key: str) -> set[str]:
    try:
        data = load_yaml_file(path)
    except ValidationProblem:
        return set()
    names: set[str] = set()
    for entry in registry_items(data, key, path, []):
        if isinstance(entry, dict) and isinstance(entry.get("name"), str):
            names.add(entry["name"])
    return names


def _import_module(
    path: Path,
    name: str,
    *,
    extra_paths: list[Path] | None = None,
    package_name: str | None = None,
) -> ModuleType | None:
    if not path.is_file():
        return None
    inserted: list[str] = []
    for extra in extra_paths or []:
        value = str(extra)
        if value not in sys.path:
            sys.path.insert(0, value)
            inserted.append(value)
    spec_name = package_name or name
    try:
        spec = importlib.util.spec_from_file_location(spec_name, path)
        if spec is None or spec.loader is None:
            return None
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        return module
    except Exception:
        return None
    finally:
        for value in inserted:
            try:
                sys.path.remove(value)
            except ValueError:
                pass


def _required_text(entry: dict[str, Any], field: str, context: str, errors: list[str]) -> str | None:
    value = entry.get(field)
    if not isinstance(value, str) or not value.strip():
        errors.append(f"{context}: field {field!r} must be a non-empty string")
        return None
    return value.strip()


def _check_unique(
    seen: dict[str, int],
    value: str,
    context: str,
    field: str,
    errors: list[str],
) -> None:
    if value in seen:
        errors.append(f"{context}: duplicate {field} {value!r}; first seen at index {seen[value]}")
    else:
        match = re.search(r"\[(\d+)\]$", context)
        seen[value] = int(match.group(1)) if match else -1


def _runtime_or_generated_path(path_value: str) -> bool:
    normalized = path_value.replace("\\", "/").strip("/")
    return normalized.startswith("dist/") or "/dist/" in normalized or "generated" in normalized


def _nonempty_field(value: Any) -> bool:
    if isinstance(value, str):
        return bool(value.strip())
    return _nonempty_string_list(value)


def _nonempty_string_list(value: Any) -> bool:
    return isinstance(value, list) and bool(value) and all(
        isinstance(item, str) and item.strip() for item in value
    )


def _visible_dirs(root: Path) -> list[Path]:
    if not root.is_dir():
        return []
    return [
        path
        for path in sorted(root.iterdir())
        if path.is_dir() and not path.name.startswith(".")
    ]


def _read_text(path: Path) -> str:
    if not path.is_file():
        return ""
    return path.read_text(encoding="utf-8")


def _backtick_values(text: str) -> list[str]:
    return re.findall(r"`([^`]+)`", text)


def _display(path: Path) -> str:
    try:
        return relpath(ROOT, path)
    except ValueError:
        return str(path)


def _clean_validation_error(exc: ValidationProblem) -> str:
    return str(exc).replace(str(ROOT) + "/", "")


def main() -> int:
    """CLI entry point."""

    result = validate_repository(ROOT)
    for warning in result.warnings:
        print(f"validate-src-invariants: WARNING: {warning}", file=sys.stderr)
    if result.errors:
        return fail_many("validate-src-invariants", result.errors)
    print(
        "validate-src-invariants: validated source registries, capability references, "
        "domain extensions, source/runtime boundary, hook runtime, validation broker, "
        "project memory, and repository intelligence invariants."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
