from __future__ import annotations

import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "validate-docs-consistency.py"


def _load_module():
    scripts_dir = str(ROOT / "scripts")
    if scripts_dir not in sys.path:
        sys.path.insert(0, scripts_dir)
    spec = importlib.util.spec_from_file_location("validate_docs_consistency_test", SCRIPT)
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _write_minimal_repo(root: Path) -> None:
    _write(
        root / "README.md",
        "\n".join(
            [
                "# Project",
                "",
                "Stable profile counts are `recommended=21`, `full=28`, and `dev=164`; generated manifests are authoritative.",
                "The marketplace index is a local/source-derived discovery asset only. Official Codex/Claude marketplace publishing is intentionally not implemented.",
            ]
        ),
    )
    _write(
        root / "docs" / "HOOKS.md",
        "\n".join(
            [
                "# Hooks",
                "",
                "Default gate modes are `sdd_material_choice=block`, `pre_edit_structure=block`, and `stop_closure=block`.",
                "Unspecified gates fallback to `warn`; ordinary advisory gates default to `warn`.",
                "Failure mode defaults to `fail_open`.",
            ]
        ),
    )
    _write(
        root / "docs" / "MARKETPLACE.md",
        "# Marketplace\n\nThis is a local discovery index. Official marketplace publishing is intentionally not implemented.\n",
    )
    _write(
        root / "docs" / "MARKETPLACE_CATALOG.md",
        "# Marketplace Catalog\n\nThis generated catalog is a local discovery view. Official marketplace publishing is intentionally not implemented.\n",
    )
    _write(root / "docs" / "SHOWCASE.md", "# Showcase\n\nGenerated by scripts/generate-examples-showcase.py.\n")
    _write(root / "docs" / "SCORECARD_DASHBOARD.md", "# Dashboard\n\nGenerated release snapshot.\n")
    _write(root / "docs" / "VALIDATION.md", "# Validation\n\nCanonical commands.\n")
    _write(
        root / "docs" / "OPEN_SOURCE_READINESS.md",
        "# Open Source Readiness\n\nNot publishable as open source until owner license and security decisions are complete.\n",
    )
    _write(root / "reports" / "public-benchmark-summary.md", "# Public\n\nGenerated release snapshot.\n")
    _write(root / "reports" / "professional-scorecard.md", "# Scorecard\n\nGenerated release snapshot.\n")
    _write(root / "reports" / "codex-live-benchmark-summary.md", "# Codex\n\nGenerated release snapshot.\n")
    _write(root / "pyproject.toml", '[project]\nlicense = { text = "Proprietary" }\n')
    _write(
        root / "config" / "open-source-release.yaml",
        "selected_license: null\ncontribution_licensing_confirmed: false\nsecurity_contact_confirmed: false\n",
    )
    _write(
        root / "src" / "hook-runtime" / "README.md",
        "\n".join(
            [
                "# Hook Runtime",
                "",
                "Default gate modes are `sdd_material_choice=block`, `pre_edit_structure=block`, and `stop_closure=block`.",
                "Unspecified gates fallback to `warn`; ordinary advisory gates default to `warn`.",
                "Failure mode defaults to `fail_open`.",
            ]
        ),
    )
    _write(
        root / "src" / "hook-runtime" / "scripts" / "changeforge_hook_policy.py",
        "\n".join(
            [
                "DEFAULT_GATE_MODES = {",
                '    "sdd_material_choice": "block",',
                '    "pre_edit_structure": "block",',
                '    "stop_closure": "block",',
                "}",
                "",
                "def gate_mode(gate_key):",
                '    return DEFAULT_GATE_MODES.get(gate_key, "warn")',
                "",
                "def failure_mode(global_failure=None):",
                '    return global_failure or "fail_open"',
            ]
        ),
    )


class ValidateDocsConsistencyTests(unittest.TestCase):
    def setUp(self) -> None:
        self.module = _load_module()

    def _errors_for(self, mutate=None) -> list[str]:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            _write_minimal_repo(root)
            if mutate is not None:
                mutate(root)
            return self.module.validate_docs_consistency(root)

    def test_stale_profile_count_fails(self) -> None:
        errors = self._errors_for(
            lambda root: _write(root / "docs" / "QUICKSTART.md", "dev has 135 foundation capabilities\n")
        )
        self.assertTrue(any("135 foundation" in error for error in errors), errors)

    def test_stale_hook_opt_in_fails(self) -> None:
        errors = self._errors_for(
            lambda root: _write(root / "docs" / "HOOKS.md", "Executable hooks remain opt-in for project installs.\n")
        )
        self.assertTrue(any("hook" in error.casefold() and "opt-in" in error.casefold() for error in errors), errors)

    def test_allowed_with_hooks_backward_compatibility_does_not_fail(self) -> None:
        errors = self._errors_for(
            lambda root: _write(
                root / "docs" / "HOOKS.md",
                "\n".join(
                    [
                        "`--with-hooks` remains accepted for backward compatibility but is no longer required.",
                        "Default gate modes are `sdd_material_choice=block`, `pre_edit_structure=block`, and `stop_closure=block`.",
                        "Unspecified gates fallback to `warn`; ordinary advisory gates default to `warn`.",
                        "Failure mode defaults to `fail_open`.",
                    ]
                ),
            )
        )
        self.assertEqual(errors, [])

    def test_codex_claude_default_warn_phrase_fails(self) -> None:
        errors = self._errors_for(
            lambda root: _write(
                root / "src" / "hook-runtime" / "README.md",
                "Codex and Claude default to warn, not block.\n",
            )
        )
        self.assertTrue(any("default to warn, not block" in error for error in errors), errors)

    def test_do_not_block_codex_claude_default_phrase_fails(self) -> None:
        errors = self._errors_for(
            lambda root: _write(
                root / "src" / "hook-runtime" / "README.md",
                "Do not block Codex or Claude by default.\n",
            )
        )
        self.assertTrue(
            any("do not block codex or claude by default" in error for error in errors),
            errors,
        )

    def test_legal_unspecified_warn_fail_open_phrase_does_not_fail(self) -> None:
        errors = self._errors_for(
            lambda root: _write(
                root / "docs" / "USAGE.md",
                "Unspecified gates fallback to warn and failure mode defaults to fail_open.\n",
            )
        )
        self.assertEqual(errors, [])

    def test_generated_doc_missing_banner_fails(self) -> None:
        errors = self._errors_for(lambda root: _write(root / "docs" / "SHOWCASE.md", "# Showcase\n\nManual text.\n"))
        self.assertTrue(any("generated/snapshot banner" in error for error in errors), errors)

    def test_local_discovery_wording_missing_fails(self) -> None:
        errors = self._errors_for(lambda root: _write(root / "docs" / "MARKETPLACE.md", "# Marketplace\n\nCatalog.\n"))
        self.assertTrue(any("local/source-derived" in error for error in errors), errors)

    def test_validation_command_duplication_fails(self) -> None:
        block = "\n".join(["python3 scripts/validate-skills.py" for _ in range(10)])
        errors = self._errors_for(lambda root: _write(root / "docs" / "RELEASE.md", f"```bash\n{block}\n```\n"))
        self.assertTrue(any("duplicated validation command block" in error for error in errors), errors)

    def test_release_gate_reference_requires_validation_section(self) -> None:
        errors = self._errors_for(
            lambda root: _write(
                root / "docs" / "RELEASE.md",
                "Run [Release Gate](VALIDATION.md#release-gate) before publication.\n",
            )
        )
        self.assertTrue(any("missing ## Release Gate" in error for error in errors), errors)

    def test_release_gate_section_satisfies_reference(self) -> None:
        def mutate(root: Path) -> None:
            _write(
                root / "docs" / "RELEASE.md",
                "Run [Release Gate](VALIDATION.md#release-gate) before publication.\n",
            )
            _write(root / "docs" / "VALIDATION.md", "# Validation\n\n## Release Gate\n\nRun Full Local.\n")

        self.assertEqual(self._errors_for(mutate), [])

    def test_fenced_validation_commands_with_comments_and_blanks_fail(self) -> None:
        commands = []
        for index in range(10):
            commands.extend(
                [
                    f"# command {index}",
                    "",
                    "python3 scripts/validate-skills.py",
                ]
            )
        block = "\n".join(commands)
        errors = self._errors_for(
            lambda root: _write(root / "docs" / "RELEASE.md", f"```bash\n{block}\n```\n")
        )
        self.assertTrue(any("fenced block has 10 commands" in error for error in errors), errors)

    def test_validation_doc_long_command_block_is_allowed(self) -> None:
        block = "\n".join(["python3 scripts/validate-skills.py" for _ in range(10)])
        errors = self._errors_for(
            lambda root: _write(root / "docs" / "VALIDATION.md", f"# Validation\n\n```bash\n{block}\n```\n")
        )
        self.assertEqual(errors, [])


if __name__ == "__main__":
    unittest.main()
