from __future__ import annotations

import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "validate-docs-consistency.py"


def _load_module():
    scripts_dir = str(ROOT / "scripts")
    if scripts_dir not in sys.path:
        sys.path.insert(0, scripts_dir)
    spec = importlib.util.spec_from_file_location("validate_docs_consistency_test", SCRIPT)
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _write_minimal_repo(root: Path) -> None:
    _write(
        root / "README.md",
        "\n".join(
            [
                "# Project",
                "",
                "Stable profile counts are `recommended=21`, `full=28`, and `dev=164`; generated manifests are authoritative.",
                "The marketplace index is a local/source-derived discovery asset only. Official Codex/Claude marketplace publishing is intentionally not implemented.",
            ]
        ),
    )
    _write(
        root / "docs" / "MARKETPLACE.md",
        "# Marketplace\n\nThis is a local discovery index. Official marketplace publishing is intentionally not implemented.\n",
    )
    _write(
        root / "docs" / "MARKETPLACE_CATALOG.md",
        "# Marketplace Catalog\n\nThis generated catalog is a local discovery view. Official marketplace publishing is intentionally not implemented.\n",
    )
    _write(root / "docs" / "SHOWCASE.md", "# Showcase\n\nGenerated by scripts/generate-examples-showcase.py.\n")
    _write(root / "docs" / "SCORECARD_DASHBOARD.md", "# Dashboard\n\nGenerated release snapshot.\n")
    _write(root / "docs" / "VALIDATION.md", "# Validation\n\nCanonical commands.\n")
    _write(
        root / "docs" / "OPEN_SOURCE_READINESS.md",
        "# Open Source Readiness\n\nNot publishable as open source until owner license and security decisions are complete.\n",
    )
    _write(root / "reports" / "public-benchmark-summary.md", "# Public\n\nGenerated release snapshot.\n")
    _write(root / "reports" / "professional-scorecard.md", "# Scorecard\n\nGenerated release snapshot.\n")
    _write(root / "reports" / "codex-live-benchmark-summary.md", "# Codex\n\nGenerated release snapshot.\n")
    _write(root / "pyproject.toml", '[project]\nlicense = { text = "Proprietary" }\n')
    _write(
        root / "config" / "open-source-release.yaml",
        "selected_license: null\ncontribution_licensing_confirmed: false\nsecurity_contact_confirmed: false\n",
    )


class ValidateDocsConsistencyTests(unittest.TestCase):
    def setUp(self) -> None:
        self.module = _load_module()

    def _errors_for(self, mutate=None) -> list[str]:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            _write_minimal_repo(root)
            if mutate is not None:
                mutate(root)
            return self.module.validate_docs_consistency(root)

    def test_stale_profile_count_fails(self) -> None:
        errors = self._errors_for(
            lambda root: _write(root / "docs" / "QUICKSTART.md", "dev has 135 foundation capabilities\n")
        )
        self.assertTrue(any("135 foundation" in error for error in errors), errors)

    def test_stale_hook_opt_in_fails(self) -> None:
        errors = self._errors_for(
            lambda root: _write(root / "docs" / "HOOKS.md", "Executable hooks remain opt-in for project installs.\n")
        )
        self.assertTrue(any("hook" in error.casefold() and "opt-in" in error.casefold() for error in errors), errors)

    def test_allowed_with_hooks_backward_compatibility_does_not_fail(self) -> None:
        errors = self._errors_for(
            lambda root: _write(
                root / "docs" / "HOOKS.md",
                "`--with-hooks` remains accepted for backward compatibility but is no longer required.\n",
            )
        )
        self.assertEqual(errors, [])

    def test_generated_doc_missing_banner_fails(self) -> None:
        errors = self._errors_for(lambda root: _write(root / "docs" / "SHOWCASE.md", "# Showcase\n\nManual text.\n"))
        self.assertTrue(any("generated/snapshot banner" in error for error in errors), errors)

    def test_local_discovery_wording_missing_fails(self) -> None:
        errors = self._errors_for(lambda root: _write(root / "docs" / "MARKETPLACE.md", "# Marketplace\n\nCatalog.\n"))
        self.assertTrue(any("local/source-derived" in error for error in errors), errors)

    def test_validation_command_duplication_fails(self) -> None:
        block = "\n".join(["python3 scripts/validate-skills.py" for _ in range(10)])
        errors = self._errors_for(lambda root: _write(root / "docs" / "RELEASE.md", f"```bash\n{block}\n```\n"))
        self.assertTrue(any("duplicated validation command block" in error for error in errors), errors)


if __name__ == "__main__":
    unittest.main()
