from __future__ import annotations

import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "validate-docs-consistency.py"


def _load_module():
    scripts_dir = str(ROOT / "scripts")
    if scripts_dir not in sys.path:
        sys.path.insert(0, scripts_dir)
    spec = importlib.util.spec_from_file_location("validate_docs_consistency_test", SCRIPT)
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _write_minimal_repo(root: Path) -> None:
    hook_policy_text = "\n".join(
        [
            "Codex and Claude block SDD material choice and pre-edit structure by default where supported.",
            "Stop closure is advisory by default: it records missing route/stage/validation/review evidence as closure risk and telemetry facts, but it does not force continuation or block final handoff unless a maintainer explicitly overrides the policy.",
            "Hook runtime failures still fail open unless explicitly configured fail-closed.",
            "Unspecified gates fallback to warn.",
        ]
    )
    _write(
        root / "README.md",
        "\n".join(
            [
                "# Project",
                "",
                "Stable profile counts are `recommended=21`, `full=28`, and `dev=164`; generated manifests are authoritative.",
                "The marketplace index is a local/source-derived discovery asset only. Official Codex/Claude marketplace publishing is intentionally not implemented.",
            ]
        ),
    )
    _write(
        root / "docs" / "HOOKS.md",
        "# Hooks\n\n" + hook_policy_text + "\n",
    )
    _write(
        root / "docs" / "MARKETPLACE.md",
        "# Marketplace\n\nThis is a local discovery index. Official marketplace publishing is intentionally not implemented.\n",
    )
    _write(
        root / "docs" / "MARKETPLACE_CATALOG.md",
        "# Marketplace Catalog\n\nThis generated catalog is a local discovery view. Official marketplace publishing is intentionally not implemented.\n",
    )
    _write(root / "docs" / "SHOWCASE.md", "# Showcase\n\nGenerated by scripts/generate-examples-showcase.py.\n")
    _write(root / "docs" / "SCORECARD_DASHBOARD.md", "# Dashboard\n\nGenerated release snapshot.\n")
    _write(root / "docs" / "VALIDATION.md", "# Validation\n\nCanonical commands.\n")
    _write(
        root / "docs" / "OPEN_SOURCE_READINESS.md",
        "# Open Source Readiness\n\nMIT licensed and ready for public open-source publication when validation passes.\n",
    )
    _write(root / "reports" / "public-benchmark-summary.md", "# Public\n\nGenerated release snapshot.\n")
    _write(root / "reports" / "professional-scorecard.md", "# Scorecard\n\nGenerated release snapshot.\n")
    _write(root / "reports" / "codex-live-benchmark-summary.md", "# Codex\n\nGenerated release snapshot.\n")
    _write(root / "LICENSE", "MIT License\n\nPermission is hereby granted, free of charge\nTHE SOFTWARE IS PROVIDED \"AS IS\"\n")
    _write(root / "pyproject.toml", '[project]\nlicense = { text = "MIT" }\n')
    _write(
        root / "config" / "open-source-release.yaml",
        "selected_license: MIT\ncontribution_licensing_confirmed: true\nsecurity_contact_confirmed: true\n",
    )
    _write(
        root / "src" / "hook-runtime" / "README.md",
        "# Hook Runtime\n\n" + hook_policy_text + "\n",
    )
    _write(
        root / "src" / "hook-runtime" / "scripts" / "changeforge_hook_policy.py",
        "\n".join(
            [
                "DEFAULT_GATE_MODES = {",
                '    "sdd_material_choice": "block",',
                '    "pre_edit_structure": "block",',
                "}",
                "",
                "def gate_mode(gate_key):",
                '    return DEFAULT_GATE_MODES.get(gate_key, "warn")',
                "",
                "def failure_mode(global_failure=None):",
                '    return global_failure or "fail_open"',
            ]
        ),
    )


class ValidateDocsConsistencyTests(unittest.TestCase):
    def setUp(self) -> None:
        self.module = _load_module()

    def _errors_for(self, mutate=None) -> list[str]:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            _write_minimal_repo(root)
            if mutate is not None:
                mutate(root)
            return self.module.validate_docs_consistency(root)

    def test_stale_profile_count_fails(self) -> None:
        errors = self._errors_for(
            lambda root: _write(root / "docs" / "QUICKSTART.md", "dev has 135 foundation capabilities\n")
        )
        self.assertTrue(any("135 foundation" in error for error in errors), errors)

    def test_stale_hook_opt_in_fails(self) -> None:
        errors = self._errors_for(
            lambda root: _write(root / "docs" / "HOOKS.md", "Executable hooks remain opt-in for project installs.\n")
        )
        self.assertTrue(any("hook" in error.casefold() and "opt-in" in error.casefold() for error in errors), errors)

    def test_allowed_with_hooks_backward_compatibility_does_not_fail(self) -> None:
        errors = self._errors_for(
            lambda root: _write(
                root / "docs" / "HOOKS.md",
                "\n".join(
                    [
                        "`--with-hooks` remains accepted for backward compatibility but is no longer required.",
                        "Codex and Claude block SDD material choice and pre-edit structure by default where supported.",
                        "Stop closure is advisory by default and records missing evidence as closure risk, but it does not force continuation or block final handoff unless explicitly overridden.",
                        "Unspecified gates fallback to warn.",
                        "Hook runtime failures still fail open unless explicitly configured fail-closed.",
                    ]
                ),
            )
        )
        self.assertEqual(errors, [])

    def test_codex_claude_default_warn_phrase_fails(self) -> None:
        errors = self._errors_for(
            lambda root: _write(
                root / "src" / "hook-runtime" / "README.md",
                "Codex and Claude default to warn, not block.\n",
            )
        )
        self.assertTrue(any("default to warn, not block" in error for error in errors), errors)

    def test_do_not_block_codex_claude_default_phrase_fails(self) -> None:
        errors = self._errors_for(
            lambda root: _write(
                root / "src" / "hook-runtime" / "README.md",
                "Do not block Codex or Claude by default.\n",
            )
        )
        self.assertTrue(
            any("do not block codex or claude by default" in error for error in errors),
            errors,
        )

    def test_legal_unspecified_warn_fail_open_phrase_does_not_fail(self) -> None:
        errors = self._errors_for(
            lambda root: _write(
                root / "docs" / "USAGE.md",
                "Unspecified gates fallback to warn and failure mode defaults to fail_open.\n",
            )
        )
        self.assertEqual(errors, [])

    def test_minimal_repo_is_consistent(self) -> None:
        self.assertEqual(self._errors_for(), [])

    def test_stop_closure_policy_defaults_to_block_fails(self) -> None:
        errors = self._errors_for(
            lambda root: _write(root / "docs" / "HOOKS.md", "Stop closure policy defaults to block.\n")
        )
        self.assertTrue(any("Stop closure block-default" in error for error in errors), errors)

    def test_stop_closure_block_config_phrase_fails(self) -> None:
        errors = self._errors_for(lambda root: _write(root / "docs" / "HOOKS.md", "stop_closure: block\n"))
        self.assertTrue(any("stop_closure: block" in error for error in errors), errors)

    def test_stop_closure_advisory_phrase_does_not_fail(self) -> None:
        errors = self._errors_for(
            lambda root: _write(
                root / "docs" / "USAGE.md",
                "Stop closure is advisory by default and records missing evidence as closure risk.\n",
            )
        )
        self.assertEqual(errors, [])

    def test_hook_policy_stop_closure_block_default_fails(self) -> None:
        errors = self._errors_for(
            lambda root: _write(
                root / "src" / "hook-runtime" / "scripts" / "changeforge_hook_policy.py",
                "\n".join(
                    [
                        "DEFAULT_GATE_MODES = {",
                        '    "sdd_material_choice": "block",',
                        '    "pre_edit_structure": "block",',
                        '    "stop_closure": "block",',
                        "}",
                        "",
                        "def gate_mode(gate_key):",
                        '    return DEFAULT_GATE_MODES.get(gate_key, "warn")',
                        "",
                        "def failure_mode(global_failure=None):",
                        '    return global_failure or "fail_open"',
                    ]
                ),
            )
        )
        self.assertTrue(any("DEFAULT_GATE_MODES must not set stop_closure" in error for error in errors), errors)

    def test_missing_license_fails(self) -> None:
        errors = self._errors_for(lambda root: (root / "LICENSE").unlink())
        self.assertTrue(any("missing root MIT license" in error for error in errors), errors)

    def test_pyproject_proprietary_fails(self) -> None:
        errors = self._errors_for(lambda root: _write(root / "pyproject.toml", '[project]\nlicense = { text = "Proprietary" }\n'))
        self.assertTrue(any("pyproject.toml" in error and "Proprietary" in error for error in errors), errors)

    def test_selected_license_null_fails(self) -> None:
        errors = self._errors_for(
            lambda root: _write(
                root / "config" / "open-source-release.yaml",
                "selected_license: null\ncontribution_licensing_confirmed: true\nsecurity_contact_confirmed: true\n",
            )
        )
        self.assertTrue(any("selected_license must be MIT" in error for error in errors), errors)

    def test_owner_license_decision_pending_doc_fails(self) -> None:
        errors = self._errors_for(
            lambda root: _write(root / "docs" / "OPEN_SOURCE_READINESS.md", "Owner license decision pending.\n")
        )
        self.assertTrue(any("owner license decision" in error for error in errors), errors)

    def test_generated_doc_missing_banner_fails(self) -> None:
        errors = self._errors_for(lambda root: _write(root / "docs" / "SHOWCASE.md", "# Showcase\n\nManual text.\n"))
        self.assertTrue(any("generated/snapshot banner" in error for error in errors), errors)

    def test_local_discovery_wording_missing_fails(self) -> None:
        errors = self._errors_for(lambda root: _write(root / "docs" / "MARKETPLACE.md", "# Marketplace\n\nCatalog.\n"))
        self.assertTrue(any("local/source-derived" in error for error in errors), errors)

    def test_validation_command_duplication_fails(self) -> None:
        block = "\n".join(["python3 scripts/validate-skills.py" for _ in range(10)])
        errors = self._errors_for(lambda root: _write(root / "docs" / "RELEASE.md", f"```bash\n{block}\n```\n"))
        self.assertTrue(any("duplicated validation command block" in error for error in errors), errors)

    def test_release_gate_reference_requires_validation_section(self) -> None:
        errors = self._errors_for(
            lambda root: _write(
                root / "docs" / "RELEASE.md",
                "Run [Release Gate](VALIDATION.md#release-gate) before publication.\n",
            )
        )
        self.assertTrue(any("missing ## Release Gate" in error for error in errors), errors)

    def test_release_gate_section_satisfies_reference(self) -> None:
        def mutate(root: Path) -> None:
            _write(
                root / "docs" / "RELEASE.md",
                "Run [Release Gate](VALIDATION.md#release-gate) before publication.\n",
            )
            _write(root / "docs" / "VALIDATION.md", "# Validation\n\n## Release Gate\n\nRun Full Local.\n")

        self.assertEqual(self._errors_for(mutate), [])

    def test_fenced_validation_commands_with_comments_and_blanks_fail(self) -> None:
        commands = []
        for index in range(10):
            commands.extend(
                [
                    f"# command {index}",
                    "",
                    "python3 scripts/validate-skills.py",
                ]
            )
        block = "\n".join(commands)
        errors = self._errors_for(
            lambda root: _write(root / "docs" / "RELEASE.md", f"```bash\n{block}\n```\n")
        )
        self.assertTrue(any("fenced block has 10 commands" in error for error in errors), errors)

    def test_validation_doc_long_command_block_is_allowed(self) -> None:
        block = "\n".join(["python3 scripts/validate-skills.py" for _ in range(10)])
        errors = self._errors_for(
            lambda root: _write(root / "docs" / "VALIDATION.md", f"# Validation\n\n```bash\n{block}\n```\n")
        )
        self.assertEqual(errors, [])


if __name__ == "__main__":
    unittest.main()
